docs/adr/0018-project-and-namespace-naming-convention.md
docs/adr/0021-deploy-database-schema-changes.md
docs/adr/README.md

Please review the "database schema changes" ADR.  This is something we'll need to implement in the near future.

added database schema changes adr

---

.github/README.md
.gitignore
README.md
docs/README.md
terraform/README.md
terraform/backend.tfvars.example
terraform/terraform.tfvars.example

Devops: [AB#156891](https://dfe-ssp.visualstudio.com/3b5b3e9f-31ab-4776-8acf-15724e34e45b/_workitems/edit/156891)
Note: Terraform has not been run against the Azure env so will still show the plan within the PR

Added some Terraform/GitHub documentation

---

terraform/main-hosting.tf

DevOps: #AB156891
Updated TF config to turn on container registry

turned on container registry

---

src/Dfe.PlanTech.Domain/Questionnaire/Interfaces/ICategory.cs
src/Dfe.PlanTech.Web/TagHelpers/TaskList/BaseTaskListTagHelper.cs
src/Dfe.PlanTech.Web/TagHelpers/TaskList/TagColour.cs
src/Dfe.PlanTech.Web/TagHelpers/TaskList/TaskListItemNameTagHelper.cs
src/Dfe.PlanTech.Web/TagHelpers/TaskList/TaskListItemTagHelper.cs
src/Dfe.PlanTech.Web/TagHelpers/TaskList/TaskListTagHelper.cs
src/Dfe.PlanTech.Web/TagHelpers/TaskList/TaskListTagTagHelper.cs
src/Dfe.PlanTech.Web/Views/Shared/Questionnaire/Category.cshtml
src/Dfe.PlanTech.Web/Views/Shared/_Layout.cshtml
src/Dfe.PlanTech.Web/wwwroot/css/app-task-list.css
tests/Dfe.PlanTech.Web.UnitTests/TagHelpers/TaskListTagTagHelperTests.cs
tests/Dfe.PlanTech.Web.UnitTests/TestHelpers/GetTagHelperString.cs

**Features**:
- Adds section list for categories
- Current status (`NOT STARTED` due to lack of database functionality currently)
- Links to somewhere (not valid links currently)
- Displayed using GDS's `task-list` pattern

feat: Add Category Section List

---

src/Dfe.PlanTech.Domain/Content/Models/ComponentDropDown.cs
src/Dfe.PlanTech.Web/Views/Shared/Components/ComponentDropDown.cshtml

- Content added into Contentful for the drop down and drop down content.
- Code added into source to match drop down content.

feat: Added component for displaying drop down

---

src/Dfe.PlanTech.Web/Views/Shared/_Layout.cshtml

**Features**:
- Adds service name (`Plan technology for your school`) to page layout header. Completes 160935

feat: Add service name to header

---

src/Dfe.PlanTech.Web/Controllers/PagesController.cs

Fixes possible null reference issue, by defaulting string to "/" if null.

fix: Possible null reference argument

---

src/Dfe.PlanTech.Infrastructure.Contentful/Dfe.PlanTech.Infrastructure.Contentful.csproj
src/Dfe.PlanTech.Infrastructure.Contentful/Helpers/ContentfulSetup.cs
src/Dfe.PlanTech.Web/Dfe.PlanTech.Web.csproj
src/Dfe.PlanTech.Web/Helpers/HttpClientPolicyExtensions.cs
src/Dfe.PlanTech.Web/Program.cs

**Features**:
- Adds Polly retry policy for Contentful requests
_Notes: Doesn't have any sort of config (e.g. how many retries, how frequent, minutes, etc.); to be added in future_

feat: Add Polly Policy

---

src/Dfe.PlanTech.Application/Persistence/Interfaces/IContentRepository.cs
src/Dfe.PlanTech.Application/Questionnaire/Queries/GetQuestionQuery.cs
src/Dfe.PlanTech.Infrastructure.Contentful/Persistence/ContentfulRepository.cs
src/Dfe.PlanTech.Infrastructure.Contentful/Persistence/QueryBuilders.cs
src/Dfe.PlanTech.Web/Controllers/QuestionsController.cs
tests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests/Persistence/ContentfulRepositoryTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Controllers/QuestionsControllerTests.cs

- Adds unit tests for Questions Controller
- Improves unit tests for Contentful repository
- Improves "GetEntityById" functionality for Contentful repository

tests: Questions Pages/Routing

---

docs/adr/0023-executing-terraform-within-github-workflows.md
docs/adr/0024-caching.md
docs/adr/README.md
src/Dfe.PlanTech.Application/Caching/Interfaces/ICacher.cs
src/Dfe.PlanTech.Domain/Caching/Interfaces/ICacheOptions.cs
src/Dfe.PlanTech.Domain/Caching/Models/CacheOptions.cs
src/Dfe.PlanTech.Web/Helpers/Cacher.cs
src/Dfe.PlanTech.Web/Program.cs
tests/Dfe.PlanTech.Web.UnitTests/Helpers/CacherTests.cs

- Adds a `Cacher` class around `IMemoryCache` functionality
- Adds caching to `Dfe.PlanTech.Web` project
_Notes: Need this for my plan for `Back` functionality so added_.

feat: Add caching

---

tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/components/dropdown.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/components/expandable-section.cy.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/landing-page.cy.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/question-page.cy.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/self-assessment.cy.js

- Improve and expand tests for `Landing` page
- Add `Expandable Section` tests for Dropdown component
- Add E2E tests for `Self-Assessment Categories` page
- Add E2E tests for `Question` page

tests: E2E Tests

---

src/Dfe.PlanTech.Application/Content/Queries/GetPageQuery.cs
src/Dfe.PlanTech.Application/Questionnaire/Queries/GetQuestionQuery.cs
src/Dfe.PlanTech.Web/Controllers/PagesController.cs
src/Dfe.PlanTech.Web/Controllers/QuestionsController.cs
tests/Dfe.PlanTech.Web.UnitTests/Controllers/PagesControllerTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Controllers/QuestionsControllerTests.cs

- Adds cancellation tokens to most actions

feat: Add cancellation tokens

---

src/Dfe.PlanTech.Web/Program.cs
src/Dfe.PlanTech.Web/ProgramExtensions.cs

- Moves services DI setup 
- Moves caching DI setup

minor: Refactor services setup

---

.github/workflows/build-and-push-image.yml

- Remove env variables on deployment, as moved to KV

cicd: Remove env vars for deployment

---

src/Dfe.PlanTech.Application/Caching/Interfaces/ICacher.cs
src/Dfe.PlanTech.Web/Helpers/Cacher.cs
tests/Dfe.PlanTech.Web.UnitTests/Helpers/CacherTests.cs

- Adds method for setting value using the default cache options time to live

feat: Add set using default cache options

---

src/Dfe.PlanTech.Infrastructure.Contentful/Dfe.PlanTech.Infrastructure.Contentful.csproj
src/Dfe.PlanTech.Web/Dfe.PlanTech.Web.csproj
src/Dfe.PlanTech.Web/Program.cs

- added Azure KeyVault secrets to the config for the app, pulled from the Azure KV instance in dev resource group

WIP - Azure key vault env secrets

---

tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/components/back-button.cy.js

- Decodes URI to ensure matches

fix: Fix Back Button Tests

---

src/Dfe.PlanTech.Application/Caching/Models/UrlHistory.cs
src/Dfe.PlanTech.Domain/SignIn/Interfaces/IDfeSignInConfiguration.cs
src/Dfe.PlanTech.Domain/SignIn/Models/DfeSignInConfiguration.cs
src/Dfe.PlanTech.Infrastructure.SignIn/DfeOpenIdConnectEvents.cs
src/Dfe.PlanTech.Infrastructure.SignIn/DfeSignInSetup.cs
src/Dfe.PlanTech.Infrastructure.SignIn/README.md
src/Dfe.PlanTech.Web/Middleware/UrlHistoryMiddleware.cs
src/Dfe.PlanTech.Web/appsettings.json
tests/Dfe.PlanTech.Web.UnitTests/Middleware/UrlHistoryMiddlewareTests.cs

- Fixes issue with back button caused by work on Check Your Answers page.

fix: Back button re-direct

---

docs/adr/0024-caching.md

- Adds decision on using `Distributed Caching` using `SQL Server` for caching ADR
Note: I've marked this as `accepted`, because if you all accept this PR then I will consider it accepted. If we need a further discussion on this, then please obviously don't accept it!

docs: Update Caching ADR

---

src/Dfe.PlanTech.Infrastructure.SignIn/DfeOpenIdConnectEvents.cs
src/Dfe.PlanTech.Infrastructure.SignIn/DfeSignInSetup.cs
src/Dfe.PlanTech.Web/Program.cs

- Re-writes the signout re-direct URI on signout, to fix issue with container app vs front-door URI mismatch.

fix: Fix signout redirect URI

---

terraform/key-vault.tf
terraform/locals.tf
terraform/scripts/add-keyvault-service-endpoint-to-app.sh
terraform/terraform-configuration.md
terraform/vnet-add-kv-service-endpoint.tf

- Adds `Microsoft.Keyvault` service endpoint to VN Subnet.
- Restricts access to KeyVault to subnet

feat: Add KV Service Endpoint to Subnet

---

.github/actions/post-terraform-results/action.yml
.github/workflows/terraform-pr-check.yml

DevOps: [AB#162563](https://dfe-ssp.visualstudio.com/3b5b3e9f-31ab-4776-8acf-15724e34e45b/_workitems/edit/162563)
* updated TF PR check to use secret project name
* also updated post-terraform-results to remove plan details as this could exposes azure resource names

updated DFE_PROJECT_NAME to use secret version

---

src/Dfe.PlanTech.Infrastructure.SignIn/README.md
terraform/key-vault.tf

- Adds information on requirement for running in https with DSi 
- Adds instructions on how to do so locally

docs: Add https instructions for DSi

---

terraform/key-vault.tf
tests/Dfe.PlanTech.Web.E2ETests/cypress.config.js
tests/Dfe.PlanTech.Web.E2ETests/cypress.env.json.example
tests/Dfe.PlanTech.Web.E2ETests/cypress/commands/login.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/components/back-button.cy.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/landing-page.cy.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/question-page.cy.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/self-assessment.cy.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/support/commands.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/support/e2e.js

* Adds login functionality to authorised pages
_Note: Does not add to workflow (will require secret management of some form), so tests will still fail there_

feat: Add login to E2E Tests

---

.github/workflows/build-and-push-image.yml

DevOps: [AB#162580](https://dfe-ssp.visualstudio.com/3b5b3e9f-31ab-4776-8acf-15724e34e45b/_workitems/edit/162580)
uncommented software deployment

fixed workflow - uncommented code

---

src/Dfe.PlanTech.Domain/Questionnaire/Models/SubmitAnswerDto.cs
src/Dfe.PlanTech.Web/Controllers/QuestionsController.cs
src/Dfe.PlanTech.Web/Program.cs
src/Dfe.PlanTech.Web/Views/Questions/Question.cshtml
src/Dfe.PlanTech.Web/appsettings.json
tests/Dfe.PlanTech.Web.UnitTests/Controllers/QuestionsControllerTests.cs

DevOps: [164391](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/164391/)
Added functionality for the question page where the "Save and continue" button will only navigate to the next page only when a radio item answer has been selected.

feat/164391: Save and continue requires an answer to be selected

---

.github/workflows/build-and-push-image.yml

DevOps: [AB#162580](https://dfe-ssp.visualstudio.com/3b5b3e9f-31ab-4776-8acf-15724e34e45b/_workitems/edit/162580)
added actions/checkout@v3 to deploy-image and tested deployment.  Failing on E2E tests now.

added actions/checkout@v3 to deploy-image

---

.github/actions/whats-my-ip-address/action.yml

DevOps: [AB#162541](https://dfe-ssp.visualstudio.com/3b5b3e9f-31ab-4776-8acf-15724e34e45b/_workitems/edit/162541)
* updated whats-my-ip-address action to make it more robust by including retry logic

updated whats-my-ip-address action to make it more robust

---

src/Dfe.PlanTech.DatabaseUpgrader/Dfe.PlanTech.DatabaseUpgrader.csproj
src/Dfe.PlanTech.DatabaseUpgrader/Program.cs
src/Dfe.PlanTech.DatabaseUpgrader/StoredProcs/SP_ReadMe.sql

DevOps: [AB#158119](https://dfe-ssp.visualstudio.com/3b5b3e9f-31ab-4776-8acf-15724e34e45b/_workitems/edit/158119)
* Added functionality to handle stored procs within DbUp
Note
* Stored procs are ALWAYS executed 
* For maintainability purposes, do not include multiple stored procs per file.

Added stored procs upgrader

---

src/Dfe.PlanTech.Domain/Questionnaire/Enums/Maturity.cs
src/Dfe.PlanTech.Domain/Questionnaire/Interfaces/IRecommendationPage.cs
src/Dfe.PlanTech.Domain/Questionnaire/Interfaces/ISection.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationPage.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/Section.cs
tests/Dfe.PlanTech.Web.UnitTests/Models/ComponentBuilder.cs
tests/Dfe.PlanTech.Web.UnitTests/Models/ComponentModelTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Models/IComponentBuilder.cs

- Adds `RecommendationsPage` model
- Adds `Recommendations` to Section model

feat: Add recommendations model 

---

.github/workflows/terraform-pr-check.yml
terraform/terraform-configuration.md

- If there's any changes to TF Documentation, it no longer fails but instead pushes the changes to the branch
- No longer run Terraform check on push to main

feat: Push tf docs changes

---

src/Dfe.PlanTech.Infrastructure.Contentful/Persistence/EntityResolver.cs
tests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests/Persistence/ContentfulRepositoryTests.cs
tests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests/Persistence/EntityResolverTests.cs

`EntityResolver`:
- Changes a field to private
- Adds unit tests

feat: EntityResolver Unit tests

---

.github/workflows/terraform-pr-check.yml

- Adds back the run of `Terraform PR` when pushed to main

cicd: Run terraform PR on push to main

---

src/Dfe.PlanTech.Application/Users/Commands/CreateUserCommand.cs
src/Dfe.PlanTech.Application/Users/Commands/RecordUserSigninCommand.cs
tests/Dfe.PlanTech.Application.UnitTests/Users/Commands/CreateUserCommandTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Users/Commands/RecordUserSigninCommandTests.cs

- Fix unit test for `RecordUserSignIn` where user doesn't already exist
- Fixes issue in `CreateUserCommand` where incorrect Id was returned.
- Fixes issue in `RecordUserSignIn` where incorrect Id

task: RecordUserSign in fix + tests

---

.github/workflows/terraform-pr-check.yml
terraform/locals.tf
terraform/main-hosting.tf
terraform/variables.tf

- Adds Kestrel endpoint to Container App via Terraform

feat: Add Kestrel Endpoint to Terraform

---

src/Dfe.PlanTech.Web/Dockerfile
src/Dfe.PlanTech.Web/appsettings.json
terraform/locals.tf
terraform/main-hosting.tf
terraform/terraform-configuration.md
terraform/variables.tf

Same as last PR, except somehow I reverted last PR? Sorry no idea how that happened to be honest.

fix: Docker Port Change

---

src/Dfe.PlanTech.Web/Properties/launchSettings.json
src/Dfe.PlanTech.Web/appsettings.Development.json

Fixes issue with URLs being set in multiple places causing issues with local development

fix: Remove dev kestrel settings

---

src/Dfe.PlanTech.Application/Users/Commands/RecordUserSigninCommand.cs
src/Dfe.PlanTech.Domain/SignIn/Models/Organisation.cs
src/Dfe.PlanTech.Domain/Users/Models/RecordUserSignInDto.cs
src/Dfe.PlanTech.Infrastructure.SignIn/ConnectEvents/OnTokenValidatedEvent.cs
src/Dfe.PlanTech.Infrastructure.SignIn/ConnectEvents/OnUserInformationReceivedEvent.cs
src/Dfe.PlanTech.Infrastructure.SignIn/DfeSignInSetup.cs
src/Dfe.PlanTech.Infrastructure.SignIn/Extensions/UserClaimsExtensions.cs
src/Dfe.PlanTech.Web/ProgramExtensions.cs
tests/Dfe.PlanTech.Application.UnitTests/Users/Commands/CreateUserCommandTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Users/Commands/RecordUserSigninCommandTests.cs
tests/Dfe.PlanTech.Infrastructure.SignIn.UnitTests/DfeOpenIdConnectEventsTests.cs
tests/Dfe.PlanTech.Infrastructure.SignIn.UnitTests/UserClaimsExtensionsTests.cs

- Changes where sign in is recorded, so that establishment Id is properly retrieved.

fix: Establishment Id

---

src/Dfe.PlanTech.Infrastructure.Data/DataProtectionDbContext.cs
src/Dfe.PlanTech.Web/Views/Shared/Recommendation/Recommendations.cshtml

Fixes a couple of warnings about nullability.

fix: Fix a couple of nullability warnings

---

src/Dfe.PlanTech.Infrastructure.Contentful/Content/Renderers/Models/PartRenderers/HyperlinkRenderer.cs

- Fixes missing end quote for hrefs in anchor tags.

fix: End quote for href

---

terraform/main-hosting.tf
terraform/terraform-configuration.md

- Updates the DFE container app Terraform module we are using to latest version (0.19.4)

chore: Update Terraform module

---

src/Dfe.PlanTech.Web/Views/Shared/_Footer.cshtml
src/Dfe.PlanTech.Web/Views/Shared/_Layout.cshtml

- Changes footer to match GDS formatting/styles (ul, hidden h2, etc.)
- Refactors footer to partial view

styles: Match GDS standards stylings for footer

---

.github/workflows/terraform-deploy.yml
.github/workflows/terraform-pr-check.yml

- Moves TF apply to a separate workflow, which triggers on pushes to main when changes in the "terraform" folder have been made.
**Benefits**:
- Automatic deployment to TF when needed
- Removes the consistent "deployments to ENVIRONMENT" messages on Terraform PR check

feat: Automate TF deployments

---

terraform/key-vault.tf

- Ignores expiration date changes on KeyVault secrets

tf: Ignore KeyVault expiration date

---

.github/actions/azure-ip-whitelist/action.yml
.github/actions/build-and-run-database-upgrader/action.yml
.github/workflows/build-and-deploy.yml
.github/workflows/code-pr-check.yml
.github/workflows/e2e-tests.yml
.github/workflows/matrix-deploy.yml
.github/workflows/terraform-deploy.yml
.github/workflows/terraform-pr-check.yml

- Outputs Azure CLI commands to /dev/null (i.e. the terminal output is hidden)
- Amends workflows to execute when they are changed

PR feat: output to dev null

---

docs/GitHub-Workflows.md
docs/adr/0024-caching.md
docs/adr/0026-javascript-usage.md
src/Dfe.PlanTech.Web.Node/README.md
src/README.md

- ADR for Javascript usage
- Brief explanations for various workflows
- README for Dfe.PlanTech.Web.Node
- Add missing projects to [src/README.md](src/README.md)

docs: Update various docs

---

terraform/main-hosting.tf

- Adds rate limiting WAF policy to TF

feat: Enable rate limiting WAF policy

---

src/Dfe.PlanTech.Web/Views/CheckAnswers/CheckAnswers.cshtml
src/Dfe.PlanTech.Web/Views/Shared/Questionnaire/Category.cshtml
src/Dfe.PlanTech.Web/Views/Shared/Recommendation/HomeRecommendations.cshtml

- Removes duplicate `main` element
- Removes certain elements out of `ul`
- Removes unnecessary duplicate `task-list`
- Resizes a header to be no larger than last header on page

fix: Various accessibility issues

---

docs/adr/0013-software-architecture.md
docs/adr/0016-tools-for-building-unit-tests.md
docs/adr/0019-contentful-integration.md
docs/adr/README.md

Updates several ADRs with their accepted status and outcomes.

docs: Update accepted ADRs

---

.github/workflows/terraform-deploy.yml

- Update TF version used on deploy

fix: TF version on deploy

---

.github/workflows/terraform-deploy.yml

- Amend TF deployment workflow to deploy when it itself has been modified.

feat: deploy on changes to TF deploy workflow

---

.github/workflows/matrix-deploy.yml

- Add path constraints to workflow again
- Add production to matrix

feat: Re-add workflow constraints

---

src/Dfe.PlanTech.Web/Middleware/SecurityHeadersMiddleware.cs
src/Dfe.PlanTech.Web/Program.cs
src/Dfe.PlanTech.Web/ProgramExtensions.cs
tests/Dfe.PlanTech.Web.UnitTests/Middleware/SecurityHeadersMiddlewareTests.cs

- Adds middleware that sets some response headers to prevent framejacking as raised in quality scan (ticket 175744)

fix: Middleware to prevent framejacking

---

src/Dfe.PlanTech.Domain/Questionnaire/Models/SubmitAnswerDto.cs
src/Dfe.PlanTech.Web/Controllers/QuestionsController.cs
src/Dfe.PlanTech.Web/Models/QuestionViewModel.cs
src/Dfe.PlanTech.Web/Views/Questions/Question.cshtml
tests/Dfe.PlanTech.Web.UnitTests/Controllers/QuestionsControllerTests.cs

- Adds question validation message display back on page after being removed recently

fix: Adds question validation error message back

---

.github/workflows/e2e-tests.yml
tests/Dfe.PlanTech.Web.E2ETests/.gitignore
tests/Dfe.PlanTech.Web.E2ETests/cypress.config.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/components/footer.cy.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/check-answer-page.cy.js
tests/Dfe.PlanTech.Web.E2ETests/package-lock.json
tests/Dfe.PlanTech.Web.E2ETests/package.json
tests/Dfe.PlanTech.Web.E2ETests/reporter-config.json

- Fixes exposed secret in workflow
- Fixes a possible bug with the Check Answers Page E2E tests
- Makes E2E workflow matrix with max 1 executions

feat: Add test report for Cypress

---

src/Dfe.PlanTech.Web/ViewComponents/FooterLinks.cs
tests/Dfe.PlanTech.Web.UnitTests/ViewComponents/FooterLinksComponentTests.cs

- Adds basic try/catch around fetching of navigation links in footer

feat: Add basic error handling for exception

---

src/Dfe.PlanTech.Domain/Establishments/Models/Establishment.cs
src/Dfe.PlanTech.Infrastructure.Contentful/Content/Renderers/Models/PartRenderers/TextRenderer.cs
src/Dfe.PlanTech.Web/Controllers/CookiesController.cs
src/Dfe.PlanTech.Web/Helpers/HeaderExtensions.cs
src/Dfe.PlanTech.Web/TagHelpers/FooterLinkTagHelper.cs
src/Dfe.PlanTech.Web/Views/Shared/Components/ButtonWithEntryReference.cshtml
tests/Dfe.PlanTech.Web.UnitTests/Models/ComponentBuilder.cs

Small PR to resolve some of the code smells that are present on the main branch.

chore: Resolve Code Smells

---

src/Dfe.PlanTech.Web/Routing/GetQuestionBySlugRouter.cs
tests/Dfe.PlanTech.Web.UnitTests/Routing/GetQuestionBySlugRouterTests.cs

- Fixes incorrect logic on retrieving question
- Fixes navigating to interstitial page
- Refactors code slightly to (hopefully) be more readable
- Add XML comments for clarity

fix: Routing logic bugs

---

src/Dfe.PlanTech.Application/Persistence/Interfaces/IPlanTechDbContext.cs
src/Dfe.PlanTech.Infrastructure.Data/PlanTechDbContext.cs

Removes a few unused things from the DbContext.

chore: Remove unused DB properties

---

.github/workflows/code-pr-check.yml
src/Dfe.PlanTech.Application/Content/Queries/GetNavigationQuery.cs
src/Dfe.PlanTech.Application/Questionnaire/Queries/GetSectionQuery.cs
src/Dfe.PlanTech.Application/Responses/Queries/GetLatestResponsesQuery.cs
src/Dfe.PlanTech.Application/Submissions/Commands/CalculateMaturityCommand.cs
src/Dfe.PlanTech.Domain/Content/Interfaces/IGetNavigationQuery.cs
src/Dfe.PlanTech.Domain/Questionnaire/Interfaces/IGetSectionQuery.cs
src/Dfe.PlanTech.Infrastructure.Contentful/Persistence/ContentfulRepository.cs
src/Dfe.PlanTech.Web/Controllers/RecommendationsController.cs
src/Dfe.PlanTech.Web/Models/PageViewModel.cs
src/Dfe.PlanTech.Web/Routing/GetRecommendationRouter.cs
src/Dfe.PlanTech.Web/ViewComponents/FooterLinks.cs
tests/Dfe.PlanTech.Application.UnitTests/Submissions/CalculateMaturityCommandTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Binders/PageModelBinderTests.cs

This PR combs through the codebase and ensures that requests are being done asynchronously where appropriate

refactor/180058 - Code Refactor - Async Calls

---

docs/Routers.md
src/Dfe.PlanTech.Web/Routing/CheckAnswersRouter.cs
src/Dfe.PlanTech.Web/Routing/GetRecommendationRouter.cs
tests/Dfe.PlanTech.Web.UnitTests/Routing/CheckAnswersRouterTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Routing/GetRecommendationRouterTests.cs

feat: Update routing

---

.github/workflows/build-image.yml
.github/workflows/code-pr-check.yml
.github/workflows/deploy-image.yml
.github/workflows/matrix-deploy.yml

This PR rejigs the pipeline by building the image only once and publishing it to the GitHub Container Registry, then for each environment deployment we pull the image from the GCR and publish them to the relevant Azure Container Registry, and lastly deploy the image.
Tickets Included:
[178008](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/178008) - Pipeline for Build
[181664](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/181664/) - Pipeline for Deploy Dev
[181667](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/181667/) - Pipeline for Deploy Test

CI/CD Build & Deploy Pipeline Implementation

---

.github/actions/run-e2e-tests/action.yml
.github/workflows/deploy-image.yml
.github/workflows/matrix-deploy.yml

Ticket: [feat/184003](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/184003)
Creating a new PR to test out a possible resolution to the issue with E2E tests running against the dev environment despite everything else running against the test environment in the push to the development branch.

feature/184003 - Resolve E2E Test Environment Issue

---

docs/adr/0030-storing-cms-in-db.md
docs/adr/0031-cms-db-structure.md
docs/adr/0032-classes-for-db-entities.md
docs/adr/README.md

- ADR for storing Contentful data in DB (177882)
- ADR for schema approach for storing Contentful data in DB (181543)
- ADR for coding practices for above

docs: Contentful DB ADRs

---

src/Dfe.PlanTech.Web/Views/CheckAnswers/CheckAnswers.cshtml
tests/Dfe.PlanTech.Web.E2ETests/cypress/commands/questionnaire-stages.js

Ticket: [184210](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_boards/board/t/Plan%20Tech/Stories/?workitem=184210)
This PR changes the "Save and submit" text to "Save and continue" on the Check Answers Page.

refactor/184210 - Update Save Button Label

---

src/Dfe.PlanTech.Web/Helpers/GtmConfiguration.cs
src/Dfe.PlanTech.Web/Views/Shared/_Layout.cshtml
tests/Dfe.PlanTech.Web.UnitTests/Helpers/GtmConfigurationTests.cs

- amended google analytics to come through config like GTM head/body, as google analytics need to be per environment

amend to analytics tags per env

---

.github/workflows/validate-scripts.yml

Ticket: [166201](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_boards/board/t/Plan%20Tech/Stories/?workitem=166201)
This PR adds an additional workflow which creates a temporary locally hosted database and runs the DatabaseUpgrader against it in order to verify that our scripts are working without error.
It also includes a job that runs a quality check on the SQL scripts and posts a comment highlighting any issues.

feature/166201 - Validating SQL Script Changes

---

plan-technology-for-your-school.sln
src/Dfe.PlanTech.AzureFunctions/Functions/BaseFunction.cs
src/Dfe.PlanTech.AzureFunctions/Functions/ContentfulWebHook.cs
src/Dfe.PlanTech.AzureFunctions/Functions/QueueReceiver.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/ComponentDropDownMapper.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/JsonToDbMapper.cs
src/Dfe.PlanTech.Domain/Content/Models/ComponentDropDownDbEntity.cs
src/Dfe.PlanTech.Domain/Content/Models/RichTextContentDbEntity.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Dfe.PlanTech.AzureFunctions.UnitTests.csproj
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Functions/BaseFunctionTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Functions/ContentfulWebHookTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/GlobalUsings.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Helpers/HttpHelpers.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/AnswerMapperTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/BaseMapperTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/ComponentDropDownMapperTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/HeaderMapperTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/JsonToDbMapperUnitTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/QuestionMapperTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/RichTextContentMapperTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/TextBodyMapperTests.cs

- Adds unit tests for the Dfe.PlanTech.AzureFunctions project

WIP feat: Caching unit tests

---

src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2023/20231206_1457_CreateCmsDbSchemas.sql

- Fixes problem in index creation where I renamed a column in the table but missed this in the index.

fix: Rename col in index to match renamed column

---

src/Dfe.PlanTech.Application/Content/Queries/GetNavigationQuery.cs
src/Dfe.PlanTech.Application/Persistence/Interfaces/ICmsDbContext.cs
src/Dfe.PlanTech.Domain/Content/Interfaces/IGetNavigationQuery.cs
src/Dfe.PlanTech.Domain/Content/Interfaces/INavigationLink.cs
src/Dfe.PlanTech.Domain/Content/Models/NavigationLink.cs
src/Dfe.PlanTech.Infrastructure.Data/CmsDbContext.cs
src/Dfe.PlanTech.Web/Program.cs
src/Dfe.PlanTech.Web/ProgramExtensions.cs
src/Dfe.PlanTech.Web/TagHelpers/FooterLinkTagHelper.cs
src/Dfe.PlanTech.Web/ViewComponents/FooterLinksViewComponent.cs
src/Dfe.PlanTech.Web/Views/Shared/Components/FooterLinks/Default.cshtml
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetNavigationQueryTests.cs

- Reads navigation links from database instead of Contentful

feat: Read NavigationLinks from database

---

src/Dfe.PlanTech.Web/Dfe.PlanTech.Web.csproj
src/Dfe.PlanTech.Web/ProgramExtensions.cs

Adds caching for the Contentful content from the database.

feat: Cache content from db

---

src/Dfe.PlanTech.Application/Content/Queries/GetCategorySectionsQuery.cs
src/Dfe.PlanTech.Application/Content/Queries/GetPageFromDbQuery.cs
src/Dfe.PlanTech.Application/Content/Queries/GetPageQuery.cs
src/Dfe.PlanTech.Domain/Content/Interfaces/IGetPageQuery.cs
src/Dfe.PlanTech.Web/ProgramExtensions.cs
src/Dfe.PlanTech.Web/ViewComponents/CategorySectionViewComponent.cs

- Refactors database query logic from `GetPageQuery` to own class `GetPageFromDbQuery`
- Add validation in `GetCategorySectionsQuery` to ensure that all sections have an InterstitialPage
- Adds error catching in `CategorySectionViewComponent` if a section is missing an InterstitialPage

feat: Add handling for missing interstitial page

---

src/Dfe.PlanTech.AzureFunctions/Functions/QueueReceiver.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetPageQueryTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Functions/QueueReceiverTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Controllers/CookieControllerTests.cs

- Adds error message to deadletter queue message
- Also use cancellation token for async methods

feat: add error message to deadletter queue

---

src/Dfe.PlanTech.AzureFunctions/Mappings/QuestionMapper.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/QuestionMapperTests.cs

- Adds order to answers from Question metadata

feat: Add order to answers

---

src/Dfe.PlanTech.Application/Persistence/Interfaces/ICmsDbContext.cs
src/Dfe.PlanTech.Application/Questionnaire/Queries/GetNextUnansweredQuestionQuery.cs
src/Dfe.PlanTech.Application/Questionnaire/Queries/GetSectionQuery.cs
src/Dfe.PlanTech.Application/Submissions/Queries/CheckAnswersOrNextQuestionChecker.cs
src/Dfe.PlanTech.Application/Submissions/Queries/SubmissionStatusProcessor.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/AnswerViewModelDto.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/Section.cs
src/Dfe.PlanTech.Infrastructure.Data/CmsDbContext.cs
src/Dfe.PlanTech.Web/Routing/CheckAnswersRouter.cs
src/Dfe.PlanTech.Web/Routing/GetRecommendationRouter.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetPageQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Questionnaire/Queries/GetSectionQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Submissions/Commands/SubmitAnswerCommandTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Controllers/CookieControllerTests.cs

- Retrieves section from DB instead of Contentful
- Retrieves from Contentful if erroring in DB
Completes 191316

feat: Retrieve section from DB

---

src/Dfe.PlanTech.Application/Content/Queries/GetCategorySectionsQuery.cs
src/Dfe.PlanTech.Application/Content/Queries/GetPageFromContentfulQuery.cs
src/Dfe.PlanTech.Application/Content/Queries/GetPageQuery.cs
src/Dfe.PlanTech.Application/Persistence/Interfaces/ICmsDbContext.cs
src/Dfe.PlanTech.Application/Persistence/Interfaces/IGetEntitiesOptions.cs
src/Dfe.PlanTech.Application/Persistence/Models/GetEntitiesOptions.cs
src/Dfe.PlanTech.AzureFunctions/Functions/QueueReceiver.cs
src/Dfe.PlanTech.Domain/Content/Models/Options/GetPageFromContentfulOptions.cs
src/Dfe.PlanTech.Domain/Users/Exceptions/PageNotFoundException.cs
src/Dfe.PlanTech.Infrastructure.Contentful/Persistence/QueryBuilders.cs
src/Dfe.PlanTech.Infrastructure.Data/CmsDbContext.cs
src/Dfe.PlanTech.Web/Controllers/CheckAnswersController.cs
src/Dfe.PlanTech.Web/Controllers/CookiesController.cs
src/Dfe.PlanTech.Web/Middleware/ServiceExceptionHandlerMiddleWare.cs
src/Dfe.PlanTech.Web/ProgramExtensions.cs
src/Dfe.PlanTech.Web/Routing/CheckAnswersRouter.cs
src/Dfe.PlanTech.Web/Routing/GetRecommendationRouter.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetPageFromContentfulQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetPageFromDbQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetPageQueryTests.cs
tests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests/Persistence/QueryBuilder/QueryBuilderSelectTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Controllers/CookieControllerTests.cs

Moves the logic to retrieve a page from Contentful to its own class.

refactor: Page query from Contentful

---

global.json
terraform/container-app/functions.tf

- Updates the .NET version from 7.0 to 8.0 in Azure Function via Terraform

fix: Update Azure Function dotnet version

---

src/Dfe.PlanTech.Web/Controllers/CheckAnswersController.cs
src/Dfe.PlanTech.Web/Helpers/RouteDataExtensions.cs
src/Dfe.PlanTech.Web/Views/Shared/_Layout.cshtml
tests/Dfe.PlanTech.Web.UnitTests/Helpers/RouteDataExtensionsTests.cs

- Fixes page title generation logic to use section slug
- Refactors into extension class for proper testing
- Adds minimum unit tests; probably needs more added.

fix: Check answers page title

---

contentful/export-processor/content-types/question.js
contentful/export-processor/content-types/section.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/dynamic-page-validator-readme.md
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/dynamic-page-validator.cy.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/self-assessment.cy.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/helpers/content-validators/content-validator.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/helpers/content-validators/page-validator.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/helpers/page-slugs.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/helpers/warning-validator.js

For each sub-topic:
1. Use Contentful data to find path(s) that will ensure every question in a sub-topic is visited at least once
2. Navigate through those paths
3. For each question, validate the question + answers are as expected
4. Validate check answers page matches the chosen questions + answers

tests: Navigate through every question in a sub-topic using Contentful data

---

src/Dfe.PlanTech.Application/Dfe.PlanTech.Application.csproj
src/Dfe.PlanTech.AzureFunctions/Dfe_PlanTech_AzureFunctions.csproj
src/Dfe.PlanTech.DatabaseUpgrader/Dfe.PlanTech.DatabaseUpgrader.csproj
src/Dfe.PlanTech.Infrastructure.Data/Dfe.PlanTech.Infrastructure.Data.csproj
src/Dfe.PlanTech.Web/Dfe.PlanTech.Web.csproj
tests/Dfe.PlanTech.Application.UnitTests/Dfe.PlanTech.Application.UnitTests.csproj
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Dfe.PlanTech.AzureFunctions.UnitTests.csproj
tests/Dfe.PlanTech.DataValidation.Tests/Dfe.PlanTech.DataValidation.Tests.csproj
tests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests.csproj
tests/Dfe.PlanTech.Infrastructure.SignIn.UnitTests/Dfe.PlanTech.Infrastructure.SignIn.UnitTests.csproj
tests/Dfe.PlanTech.Web.UnitTests/Dfe.PlanTech.Web.UnitTests.csproj

- Updates all Nuget packages
- Removes moq from the one project it's accidentally still in

chore: Update all nuget packages.

---

docs/GitHub-Workflows.md

- Add information about the `create-tag-release` workflow
- Add information about the `clear-user-data-from-db` workflow
Also:
- Move the Terraform workflow section down a bit to ensure in alphabetical order
- Add a ToC to the start

docs(workflows): :memo: Add workflow changes to docs

---

src/Dfe.PlanTech.Domain/Content/Models/PageDbEntity.cs
src/Dfe.PlanTech.Web/Views/Shared/_Layout.cshtml

Code was basically doing a full outer join, instead of a left join, resulting in content being duplicated multiple times.

fix: no longer duplicate content

---

.github/workflows/code-pr-check.yml
.github/workflows/create-tag-release.yml
src/Dfe.PlanTech.Application/Content/Queries/GetSubTopicRecommendationQuery.cs
src/Dfe.PlanTech.AzureFunctions/Functions/QueueReceiver.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/RecommendationChunkMapper.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/RecommendationChunkUpdater.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/RecommendationIntroMapper.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/RecommendationIntroUpdater.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/RecommendationSectionMapper.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/RecommendationSectionUpdater.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/SubtopicRecommendationMapper.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/SubtopicRecommendationUpdater.cs
src/Dfe.PlanTech.Domain/Questionnaire/Interfaces/IRecommendationsRepository.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationChunkAnswerDbEntity.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationIntroContentDbEntity.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationSectionChunkDbEntity.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/SubtopicRecommendationDbEntity.cs
src/Dfe.PlanTech.Infrastructure.Data/EntityTypeConfigurations/PageEntityTypeConfiguration.cs
src/Dfe.PlanTech.Infrastructure.Data/EntityTypeConfigurations/RecommendationChunkEntityTypeConfiguration.cs
src/Dfe.PlanTech.Infrastructure.Data/EntityTypeConfigurations/RecommendationIntroEntityTypeConfiguration.cs
src/Dfe.PlanTech.Infrastructure.Data/EntityTypeConfigurations/SectionEntityTypeConfiguration.cs
src/Dfe.PlanTech.Infrastructure.Data/Repositories/RecommendationsRepository.cs

- Should fix Azure Function mappings (pending further testing)
- Should fix the release workflow by installing latest NPM
- Fixes linting job, by removing code that was accidentally checked in

fix: :ambulance: Azure Function mappings + release workflow

---

src/Dfe.PlanTech.Domain/Questionnaire/Models/CategoryDbEntity.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/QuestionDbEntity.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/SectionDbEntity.cs

Excludes various child entity fields to prevent them being overridden unintentionally.

fix(functions): :ambulance: More Function relationship fixes

---

src/Dfe.PlanTech.AzureFunctions/Mappings/RecommendationChunkUpdater.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/RecommendationIntroUpdater.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/RecommendationSectionUpdater.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationChunkDbEntity.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationIntro.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationSection.cs

Previous fix missed a few child entities; this should (?) be the last of them
perf(functions): :zap: Remove unnecessary list allocations
Removed a few calls on `ToList()` in places where they're not needed, and an `IEnumerable` would suffice.

fix(functions): :bug: Add ignore to remaining child relationships

---

contentful/export-processor/content-types/content-types.js
contentful/export-processor/index.js
src/Dfe.PlanTech.Web/ProgramExtensions.cs
tests/Dfe.PlanTech.Web.E2ETests/cypress.config.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/dynamic-page-validator.cy.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/helpers/content-validators/button-validator.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/helpers/contentful-data-loader.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/helpers/page-slugs.js
tests/Dfe.PlanTech.Web.E2ETests/package-lock.json
tests/Dfe.PlanTech.Web.E2ETests/package.json

Not sure of what caused this, but fixes module, class, and function imports where necessary to fix the E2E tests

fix: E2E tests

---

src/Dfe.PlanTech.Web/ProgramExtensions.cs

- removed missing definition
- set to log at debug level to false

fix: EFCacheProvider breakage

---

src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationChunkDbEntity.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationIntroDbEntity.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationSectionDbEntity.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/SubtopicRecommendationDbEntity.cs

Fixes issues where relationships for recommendation content types were failing to be saved correctly.

fix: Recommendation relation updates

---

src/Dfe.PlanTech.Application/Content/Queries/GetSubTopicRecommendationFromDbQuery.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetSubTopicRecommendationFromDbQueryTests.cs

Validates that a Subtopic Recommendation has `Intros` when retrieved from the DB. Otherwise logs an error, and returns null, resulting in Contentful being queried instead.

fix: Validate Subtopic Recommendations retrieved from DB

---

docs/adr/0032-classes-for-db-entities.md
docs/adr/README.md

Added outcome to [0032-classes-for-db-entities.md](./docs/adr/0032-classes-for-db-entities.md), and marked as accepted.

docs(adrs): :memo: Update ADR 32

---

docs/adr/0027-accesibility-testing.md
docs/adr/0035-caching.md
docs/adr/0036-db-unit-tests.md

Noticed a couple of numbers in the readmes were out of sync with their filename

docs(adrs):Align decision numbers

---

contentful/export-processor/.gitignore
contentful/export-processor/migrations/post-content-to-webhook.js

Saves a stripped down version of each entry that was migrated, along with the group/batch of migrations it was a part of.
Used for debugging and ensuring migrations were ran in correct order.

feat(migrations): :sparkles: Write migrated content data

---

src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2024/20240522_1456_CreateDeleteEstablishmentDataSProc.sql

This stored procedure was originally only intended to run on dev.
However, our deployments to staging keep having issues as this is missing. It's easy enough to fix manually everytime but more reliable to add this in

fix(sql): :adhesive_bandage: Adds missing stored procedure

---

terraform/container-app/functions.tf

As advised by the ITHC (part of the `medium` for the Storage Accounts).

feat: Enables soft delete for blobs + containers on the Azure Function storage account

---

src/Dfe.PlanTech.Application/Content/Queries/GetSubTopicRecommendationQuery.cs
src/Dfe.PlanTech.Web/Controllers/CheckAnswersController.cs
src/Dfe.PlanTech.Web/Controllers/CookiesController.cs
src/Dfe.PlanTech.Web/Controllers/PagesController.cs
src/Dfe.PlanTech.Web/Controllers/QuestionsController.cs
src/Dfe.PlanTech.Web/Controllers/RecommendationsController.cs
src/Dfe.PlanTech.Web/Helpers/LogInvalidModelState.cs

Logs any invalid model states and sets prefix for each of the controllers

Fix sonar cloud highs

---

src/Dfe.PlanTech.AzureFunctions/Mappings/EntityUpdater.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/JsonToDbMapper.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/QuestionMapper.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/SectionMapper.cs
src/Dfe.PlanTech.AzureFunctions/Models/MappedEntity.cs
src/Dfe.PlanTech.AzureFunctions/Startup.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Helpers/MapperHelpers.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/QuestionMapperTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/SectionMapperTests.cs

- Remove questions from a section that are no longer in that section in Contentful
- Remove answers from questions that are no longer in that question in Contentful

fix: Remove removed contents

---

terraform/container-app/key-vault.tf
terraform/container-app/locals.tf
terraform/container-app/terraform-configuration.md

- Adds CSP secrets to our Key Vault using Terraform

:bricks:(kv): Add CSP secrets to Key Vault TF

---

src/Dfe.PlanTech.Infrastructure.SignIn/DfeOpenIdConnectEvents.cs
tests/Dfe.PlanTech.Infrastructure.SignIn.UnitTests/DfeOpenIdConnectEventsTests.cs

- Adds scheme to generated auth callback URLs
- Improves the tests around the URLs by checking if they're valid URIs, and then validating around that.

fix: Add scheme to callback URL

---

src/Dfe.PlanTech.DatabaseUpgrader/Program.cs

Ensures that the program will exit with an error code by throwing an exception if an error occurred

fix: Make DB upgrader error on error

---

tests/Dfe.PlanTech.Web.E2ETests/cypress.config.js

- Also increase retries to _3_.

change(e2e): Increase E2E test timeout by ~25%

---

src/Dfe.PlanTech.Infrastructure.Data/Repositories/RecommendationsRepository.cs
tests/Dfe.PlanTech.Infrastructure.Data.UnitTests/Repositories/RecommendationsRepositoryTests.cs

Fixes ordering of recommendation contents.

fix: Order content when mapping to parents

---

.github/workflows/validate-scripts.yml
src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2024/20240712_1400_FixAllSQLWarnings.sql

- Addresses all current high risk SQL warnings
- Changes the configuration to only check updated files rather than specific directories
These fell into 3 categories:
| Errors against a current entity                           | Most up to date issue(s)                                                                                 | Mitigation       |
| --------------------------------------------------------- | -------------------------------------------------------------------------------------------------------- | ---------------- |
| [contentful].[richtextcontentsbysubtopicrecommendationid] | [Query Anti-pattern - Join without equality] Not actually a real problem, sqlcheck doesn't like the Joins to subqueries - I think this is a bug in sqlcheck, a similar issue was raised for it last …

Fix: Address all sql warnings

---

src/Dfe.PlanTech.Web/Dockerfile

Updated dockerfile to import contentandsupport folder in order to publish to the GHCR

Updated dockerfile to import C&S project

---

.editorconfig

- Adds indentation and whitespace styling

feat: Add initial .editorconfig

---

contentful/export-processor/data-tools.js

- Fixes a couple of imports that had double extensions.

fix(contentful): Fix incorrect paths

---

src/Dfe.PlanTech.Web/appsettings.json

For consistency with service unavailable/contact us page, added the email as asked for on the ticket

Chore: update error message

---

src/Dfe.PlanTech.Web/Views/Pages/Page.cshtml
src/Dfe.PlanTech.Web/appsettings.json

Amended to the requested text following the demo ( as per the [ticket](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/216183) )

Chore: update error panel

---

docs/adr/0037-content-validation-process.md
docs/adr/README.md

Addresses ticket [#223398](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/223398)
Adds an ADR for the proposed solution to the current problems with content creation
Consider the suggested approaches and which is the most sensible, and feel free to suggest any alternative approaches
As Plan Tech has been build under the expectation that various fields can be assumed present, I believe the least risky option with the best chance of resolving the issue is option 3. So propose setting the outcome to 3

Docs(adr): Content validation process

---

contentful/export-processor/migrations/get-contents-with-references.js
contentful/export-processor/migrations/post-content-to-webhook.js

Fixes a couple of minor errors in the Contentful Data Migrator.
- Fix variable names
- Use `Map`'s `.get()` method instead of array

fix: Couple of minor fixes

---

src/Dfe.PlanTech.AzureFunctions/Mappings/EntityUpdater.cs
src/Dfe.PlanTech.AzureFunctions/Models/MappedEntity.cs
tests/Dfe.PlanTech.AzureFunctions.E2ETests/Generators/RecommendationChunkGenerator.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Models/MappedEntityTests.cs

The most recent change to the azure function was reverted to test if this was the cause of it going down, but it is due to something else, so this can be restored.

Revert "revert-last-function-change"

---

src/Dfe.PlanTech.AzureFunctions/Dfe.PlanTech.AzureFunctions.csproj

Restore temporarily reverted sdk version change

chore: revert rollback of sdk version

---

src/Dfe.ContentSupport.Web/Dfe.ContentSupport.Web.csproj
src/Dfe.PlanTech.Application/Dfe.PlanTech.Application.csproj
src/Dfe.PlanTech.DatabaseUpgrader/Dfe.PlanTech.DatabaseUpgrader.csproj
src/Dfe.PlanTech.Domain/Dfe.PlanTech.Domain.csproj
src/Dfe.PlanTech.Infrastructure.Contentful/Dfe.PlanTech.Infrastructure.Contentful.csproj
src/Dfe.PlanTech.Infrastructure.Data/Dfe.PlanTech.Infrastructure.Data.csproj
src/Dfe.PlanTech.Infrastructure.ServiceBus/Dfe.PlanTech.Infrastructure.ServiceBus.csproj
src/Dfe.PlanTech.Infrastructure.SignIn/Dfe.PlanTech.Infrastructure.SignIn.csproj
src/Dfe.PlanTech.Web/Dfe.PlanTech.Web.csproj
tests/Dfe.ContentSupport.Web.Tests/Dfe.ContentSupport.Web.Tests.csproj
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetPageQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Dfe.PlanTech.Application.UnitTests.csproj
tests/Dfe.PlanTech.CmsDbDataValidator/Dfe.PlanTech.CmsDbDataValidator.csproj
tests/Dfe.PlanTech.Domain.UnitTests/Dfe.PlanTech.Domain.UnitTests.csproj
tests/Dfe.PlanTech.Domain.UnitTests/Helpers/DateTimeFormatterTests.cs
tests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests.csproj
tests/Dfe.PlanTech.Infrastructure.Data.UnitTests/Dfe.PlanTech.Infrastructure.Data.UnitTests.csproj
tests/Dfe.PlanTech.Infrastructure.Data.UnitTests/Repositories/RecommendationsRepositoryTests.cs
tests/Dfe.PlanTech.Infrastructure.ServiceBus.UnitTests/Dfe.PlanTech.Infrastructure.ServiceBus.UnitTests.csproj
tests/Dfe.PlanTech.Infrastructure.SignIn.UnitTests/Dfe.PlanTech.Infrastructure.SignIn.UnitTests.csproj
tests/Dfe.PlanTech.UnitTests.Shared/Dfe.PlanTech.UnitTests.Shared.csproj
tests/Dfe.PlanTech.Web.SeedTestData/Dfe.PlanTech.Web.SeedTestData.csproj
tests/Dfe.PlanTech.Web.UnitTests/Dfe.PlanTech.Web.UnitTests.csproj

Package Updates
Update packages

Packages update

---

src/Dfe.PlanTech.Web/Views/Shared/Components/CategorySection/SubtopicRecommendation.cshtml

Addresses ticket [#234972](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/234972)
Fixes capitalisation for GDS requirements

fix: Fix capitalisation on button

---

.github/actions/post-pr-comment/action.yml
.github/actions/run-mutations-testing/action.yml
.github/actions/run-mutations-testing/process_mutation_report.js
.github/actions/run-mutations-testing/stryker-config.json
.github/workflows/mutations-testing.yml
.gitignore

Addresses ticket 237770
Adds a workflow for running mutations testing
- Minor change one
- Minor change two
- Minor change three
- ...
- Docs change one
Guidance/instructions for reviewing the PR. Linking to existing documentation, DevOps tickets, etc. is acceptable, but as much information as is required for testing the PR should be included/referenced.
Include things such as:
- Setting up the PR. E.g.
- Any instructions required for running the web app
- If Contentful content is required, what the changes are, what existing content could be used, etc
- Where to test, e.g. "recommendations".
- If the PR is to address a bug, how to replicate the bug
What steps are required for release, if any? E.g. Key Vault secrets, Terraform changes, etc.
Release requirement one description
- Step one
- …

feat: Add mutations testing to Github Actions

---

src/Dfe.PlanTech.Domain/Persistence/Models/ContentfulOptions.cs
src/Dfe.PlanTech.Web/Controllers/QuestionsController.cs
src/Dfe.PlanTech.Web/Controllers/RecommendationsController.cs
src/Dfe.PlanTech.Web/README.md
src/Dfe.PlanTech.Web/appsettings.Staging.json
src/Dfe.PlanTech.Web/appsettings.json

Draft pending ticket refinement + approval. Created for now so the story creator can revise story if needed.
Addresses ticket [#237416](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_boards/board/t/Team%20Build/Stories?System.IterationPath=%40currentIteration&workitem=237416)
Changes variable names to reference `UsePreviewApi` instead of `UsePreview`.
- Open the code locally 
- Run `dotnet user-secrets set Contentful:UsePreviewApi false`
- Run the solution and check that the page **does not** display any preview content.
- Stop the solution
- Run `dotnet user-secrets set Contentful:UsePreviewApi true`
- Run the solution and confirm that the page **does** display preview content.
Double check the keyvaults and remove all occurrences of `contentful_usePreview` and …

fix (237416): use preview environment variable

---

.github/workflows/contentful-backup.yml

Testing to update automatic contentful-backup - changed cron job to every hour.

Update contentful-backup cron job for test

---

src/Dfe.PlanTech.Domain/CategorySection/CategorySectionRecommendationDto.cs
src/Dfe.PlanTech.Domain/Groups/GroupsCategorySectionDto.cs
src/Dfe.PlanTech.Domain/Groups/Models/GroupsCustomRecommendationIntro.cs
src/Dfe.PlanTech.Web.Node/styles/scss/overrides.scss
src/Dfe.PlanTech.Web/Controllers/GroupsController.cs
src/Dfe.PlanTech.Web/Models/GroupsDashboardViewComponentViewModel.cs
src/Dfe.PlanTech.Web/Models/GroupsRecommendationsViewModel.cs
src/Dfe.PlanTech.Web/Program.cs
src/Dfe.PlanTech.Web/ViewComponents/GroupsDashboardViewComponent.cs
src/Dfe.PlanTech.Web/Views/Groups/Content.cshtml
src/Dfe.PlanTech.Web/Views/Groups/GroupsSchoolDashboard.cshtml
src/Dfe.PlanTech.Web/Views/Groups/Header.cshtml
src/Dfe.PlanTech.Web/Views/Groups/Pagination.cshtml
src/Dfe.PlanTech.Web/Views/Groups/Print.cshtml
src/Dfe.PlanTech.Web/Views/Groups/RecommendationPrintContent.cshtml
src/Dfe.PlanTech.Web/Views/Groups/Recommendations.cshtml
src/Dfe.PlanTech.Web/Views/Groups/RecommendationsChecklist.cshtml
src/Dfe.PlanTech.Web/Views/Groups/VerticalNavigation.cshtml
src/Dfe.PlanTech.Web/Views/Shared/Components/GroupsDashboard/GroupsSubtopicRecommendations.cshtml
src/Dfe.PlanTech.Web/Views/Shared/Components/GroupsDashboard/GroupsSubtopics.cshtml

Details will be added to groups -> development PR
Ticket for reviewing is [here](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/254055)
Addresses ticket [#](www.ticket-link.com)
High level overview of changes; one or two sentences.
The design for the ticket is based on:
- Major change one
- Major change two
- ...
- Minor change one
- Minor change two
- Minor change three
- ...
- Docs change one
Guidance/instructions for reviewing the PR. Linking to existing documentation, DevOps tickets, etc. is acceptable, but as much information as is required for testing the PR should be included/referenced.
Include things such as:
- Setting up the PR. E.g.
- Any instructions required for running the web app
- If Contentful content is required, what the changes are, …

feat(254055): groups recommendations view

---

src/Dfe.PlanTech.Web/Controllers/GroupsController.cs

Fix for assessment count on MAT school selection page to include in-progress but previously completed sections

release v2.20.0 - assessment count hot fix

---

.github/workflows/flush-redis-cache.yml

- Ability to flush the cache via github actions for dev/testing/staging
It will probably need to be merged into main and tested. 

(actions): Github workflow to flush redis cache.

---

.github/workflows/flush-redis-cache.yml

Flush redis cache yaml file fix

fixed yaml file on flush-redis-cache

---

utils/retrieve-user-data/.env.example
utils/retrieve-user-data/README.md
utils/retrieve-user-data/index.js

Addresses ticket [#263273](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/263273)
Adds retrieval of full name and organisations to user details tool
Adds name field to results
Adds organisations field to results and lists each org associated with the user, concatenated with the GIAS provider type

utils(263273): improve user details retrieval tool

---

src/Dfe.PlanTech.Web/Models/CategorySectionViewComponentViewModel.cs
src/Dfe.PlanTech.Web/ViewComponents/CategorySectionViewComponent.cs
src/Dfe.PlanTech.Web/Views/Shared/Components/CategorySection/Default.cshtml
tests/Dfe.PlanTech.Web.UnitTests/ViewComponents/CategorySectionViewComponentTests.cs

- Removed the topic count and progress text on the self-assessment page
- Added category description (same as the current MAT View)

(feat):/home page journey v1/UI changes

---

.github/workflows/matrix-deploy.yml

Addresses ticket [#TICKET-NUMBER](www.ticket-link.com)
High level overview of changes; one or two sentences.
The design for the ticket is based on:
- Major change one
- Major change two
- ...
- Minor change one
- Minor change two
- Minor change three
- ...
- Docs change one
Guidance/instructions for reviewing the PR. Linking to existing documentation, DevOps tickets, etc. is acceptable, but as much information as is required for testing the PR should be included/referenced.
Include things such as:
- Setting up the PR. E.g.
- Any instructions required for running the web app
- If Contentful content is required, what the changes are, what existing content could be used, etc
- Where to test, e.g. "recommendations".
- If the PR is to address a bug, how to replicate the bug
What steps are …

remove restrictions on running terraform plan and deploy

---

contentful/qa-visualiser/src/generate_visualisations.py
contentful/qa-visualiser/tests/test_generate_visualisations.py

Add question numbers to QA visualiser. Request from Wes. Quick fix so thought I'd do it.

feat: Add question numbers to QA visualiser

---

tests/Dfe.PlanTech.Web.E2ETests.Beta/features/accessibility-page.feature
tests/Dfe.PlanTech.Web.E2ETests.Beta/features/beta-banner.feature
tests/Dfe.PlanTech.Web.E2ETests.Beta/features/cookies.feature
tests/Dfe.PlanTech.Web.E2ETests.Beta/features/footer-links.feature
tests/Dfe.PlanTech.Web.E2ETests.Beta/features/landing-page.feature
tests/Dfe.PlanTech.Web.E2ETests.Beta/features/questions.feature
tests/Dfe.PlanTech.Web.E2ETests.Beta/features/recommendations-page.feature
tests/Dfe.PlanTech.Web.E2ETests.Beta/features/self-assessment.feature
tests/Dfe.PlanTech.Web.E2ETests.Beta/features/step_definitions/common.steps.ts
tests/Dfe.PlanTech.Web.E2ETests.Beta/features/step_definitions/recommendation-page.steps.ts
tests/Dfe.PlanTech.Web.E2ETests.Beta/features/step_definitions/self-assessment.steps.ts
tests/Dfe.PlanTech.Web.E2ETests.Beta/features/step_definitions/shortcuts.steps.ts
tests/Dfe.PlanTech.Web.E2ETests.Beta/features/unauthorised.feature
tests/Dfe.PlanTech.Web.E2ETests.Beta/login.setup.ts

Addresses ticket [#257806](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/265941)
Added recommendation page tests and amended /self-assessment to /home in other tests.

tests(257806): Create new recommendation page e2e tests

---

.github/scripts/send-expiry-alerts.py
.github/workflows/check-secret-expiry.yml

- Don't send expiry emails when there are no secrets expiring.
- Add Roger as recipient.

feat: Don't send expiry email when there are no expired keys. Add Roger to recipients.

---

src/Dfe.PlanTech.Domain/Questionnaire/Models/Category.cs
src/Dfe.PlanTech.Web/Models/CategorySectionViewComponentViewModel.cs
src/Dfe.PlanTech.Web/ViewComponents/CategorySectionViewComponent.cs
src/Dfe.PlanTech.Web/Views/Pages/Page.cshtml
src/Dfe.PlanTech.Web/Views/Shared/Components/CategorySection/Default.cshtml
src/Dfe.PlanTech.Web/Views/Shared/Components/CategorySection/Subtopics.cshtml
src/Dfe.PlanTech.Web/Views/Shared/Questionnaire/Category.cshtml
tests/Dfe.PlanTech.Web.UnitTests/ViewComponents/CategorySectionViewComponentTests.cs

Updated card view to match new progress tracking designs
Addresses ticket [#263926](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/263926)
- Updated cards and home page to match progress tracking designs
- Included category landing page routing
- Updated card status evaluation
Run locally on the branch, login and you'll be presented with the new home page design. Click any card to route to it's category landing page.
- [x ] Title uses [Angular commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [x ] Unit tests have been added/updated

263926 Added new home page card design for progress tracking

---

src/Dfe.PlanTech.Web/Views/Recommendations/CategoryLandingPage.cshtml

Addresses ticket [275128](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/275128)
High level overview of changes; one or two sentences.
Change category landing back link naming and remove js class

275128 Change category landing back link naming

---

src/Dfe.PlanTech.Application/Configuration/GoogleTagManagerServiceServiceConfiguration.cs
src/Dfe.PlanTech.Web/Attributes/MaintainUrlOnKeyNotFoundAttribute.cs
src/Dfe.PlanTech.Web/Authorisation/Policies/PageModelAuthorisationPolicy.cs
src/Dfe.PlanTech.Web/Controllers/CookiesController.cs
src/Dfe.PlanTech.Web/Handlers/UserJourneyMissingContentExceptionHandler.cs
src/Dfe.PlanTech.Web/Middleware/ServiceExceptionHandlerMiddleWare.cs
src/Dfe.PlanTech.Web/ServiceCollectionExtensions.cs
src/Dfe.PlanTech.Web/ViewBuilders/BaseViewBuilder.cs
src/Dfe.PlanTech.Web/ViewBuilders/CategoryLandingViewComponentViewBuilder.cs
src/Dfe.PlanTech.Web/ViewBuilders/CategorySectionViewComponentViewBuilder.cs
src/Dfe.PlanTech.Web/ViewBuilders/CmsViewBuilder.cs
src/Dfe.PlanTech.Web/ViewBuilders/FooterLinksViewComponentViewBuilder.cs
src/Dfe.PlanTech.Web/ViewBuilders/GroupsDashboardViewComponentViewBuilder.cs
src/Dfe.PlanTech.Web/ViewBuilders/GroupsViewBuilder.cs
src/Dfe.PlanTech.Web/ViewBuilders/PagesViewBuilder.cs
src/Dfe.PlanTech.Web/ViewBuilders/QuestionsViewBuilder.cs
src/Dfe.PlanTech.Web/ViewBuilders/RecommendationsViewBuilder.cs
src/Dfe.PlanTech.Web/ViewBuilders/ReviewAnswersViewBuilder.cs
src/Dfe.PlanTech.Web/Views/Shared/CookiesBanner/_CookieBanner.cshtml
src/Dfe.PlanTech.Web/Views/Shared/GoogleTagManager/_Body.cshtml
src/Dfe.PlanTech.Web/Views/Shared/GoogleTagManager/_Head.cshtml
src/Dfe.PlanTech.Web/Views/_ViewImports.cshtml

Fix dependency injection

---

src/Dfe.PlanTech.Core/Constants/UrlConstants.cs
src/Dfe.PlanTech.Web/Views/Pages/Page.cshtml

Added missing test slug from previous PR (274402)
- [x ] Title uses [Angular commit convention](https://www.conventionalcommits.org/en/v1.0.0/)

Add missing test slug

---

src/Dfe.PlanTech.Web/Attributes/ValidateApiKeyAttribute.cs
tests/Dfe.PlanTech.Web.UnitTests/Attributes/LogInvalidModelStateAttributeTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Attributes/MaintainUrlOnKeyNotFoundAttributeTests.cs
tests/Dfe.PlanTech.Web.UnitTests/TagHelpers/RichText/GridContainerTagHelperTests.cs
tests/Dfe.PlanTech.Web.UnitTests/TagHelpers/RichText/RichTextTagHelperTests.cs
tests/Dfe.PlanTech.Web.UnitTests/TagHelpers/TaskList/BaseTaskListTagHelperTests.cs
tests/Dfe.PlanTech.Web.UnitTests/TagHelpers/TaskList/TaskListItemNameTagHelperTests.cs
tests/Dfe.PlanTech.Web.UnitTests/TagHelpers/TaskList/TaskListItemTagHelper.cs.cs
tests/Dfe.PlanTech.Web.UnitTests/TagHelpers/TaskList/TaskListTagHelper.cs
tests/Dfe.PlanTech.Web.UnitTests/TagHelpers/TaskList/TaskListTagTagHelperTests.cs

feat: Unit tests for Web.Attributes

---

tests/Dfe.PlanTech.Web.UnitTests/Background/BackgroundTaskHostedServiceTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Background/BackgroundTaskQueueTests.cs

feat: Unit tests for Web.Background

---

src/Dfe.PlanTech.Web/Factories/ComponentViewsFactory.cs
src/Dfe.PlanTech.Web/Helpers/CacheHelper.cs
src/Dfe.PlanTech.Web/Helpers/PageRedirecter.cs
src/Dfe.PlanTech.Web/Helpers/RouteDataExtensions.cs
src/Dfe.PlanTech.Web/Helpers/ViewHelpers.cs
src/Dfe.PlanTech.Web/ServiceCollectionExtensions.cs
src/Dfe.PlanTech.Web/Views/Shared/Components/PageComponentFactory.cshtml
tests/Dfe.PlanTech.Web.UnitTests/Factories/ComponentViewsFactoryTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Handlers/UserJourneyMissingContentExceptionHandlerTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Helpers/CacheHelperTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Helpers/CustomRequestDimensionsTelemetryInitializerTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Helpers/HeaderExtensionsTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Helpers/HttpClientPolicyExtensionsTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Helpers/PageRedirecterTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Helpers/RichTextMarkExtensionsTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Helpers/RouteDataExtensionsTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Helpers/ViewHelpersTests.cs

Unit tests for Web.Factories, Web.Handlers, and Web.Helpers

feat: Unit tests for Web.Factories, Web.Handlers, and Web.Helpers

---

tests/Dfe.PlanTech.Web.UnitTests/Dfe.PlanTech.Web.UnitTests.csproj
tests/Dfe.PlanTech.Web.UnitTests/Middleware/HeadRequestMiddlewareTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Middleware/RobotsTxtMiddlewareTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Middleware/SecurityHeadersMiddlewareTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Middleware/ServiceExceptionHandlerMiddlewareTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Middleware/UserAuthorisationMiddlewareResultHandlerTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Middleware/UserOrganisationAuthorisationHandlerTests.cs

Add unit tests to web for middleware

add unit tests for middlware in web project

---

src/Dfe.PlanTech.Web/ServiceCollectionExtensions.cs
src/Dfe.PlanTech.Web/ViewBuilders/CategoryLandingViewComponentViewBuilder.cs
src/Dfe.PlanTech.Web/ViewBuilders/CategorySectionViewComponentViewBuilder.cs
src/Dfe.PlanTech.Web/ViewBuilders/FooterLinksViewComponentViewBuilder.cs
src/Dfe.PlanTech.Web/ViewBuilders/GroupsDashboardViewComponentViewBuilder.cs
src/Dfe.PlanTech.Web/ViewBuilders/Interfaces/ICategoryLandingViewComponentViewBuilder.cs
src/Dfe.PlanTech.Web/ViewBuilders/Interfaces/ICategorySectionViewComponentViewBuilder.cs
src/Dfe.PlanTech.Web/ViewBuilders/Interfaces/IFooterLinksViewComponentViewBuilder.cs
src/Dfe.PlanTech.Web/ViewBuilders/Interfaces/IGroupsDashboardViewComponentViewBuilder.cs
src/Dfe.PlanTech.Web/ViewComponents/CategoryLandingViewComponent.cs
src/Dfe.PlanTech.Web/ViewComponents/CategorySectionViewComponent.cs
src/Dfe.PlanTech.Web/ViewComponents/FooterLinksViewComponent.cs
src/Dfe.PlanTech.Web/ViewComponents/GroupsDashboardViewComponent.cs
tests/Dfe.PlanTech.Web.UnitTests/Authorisation/Filters/ApiKeyAuthorisationFilterTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Authorisation/Policies/PageModelAuthorisationPolicyTests.cs
tests/Dfe.PlanTech.Web.UnitTests/TagHelpers/FooterLinkTagHelperTests.cs
tests/Dfe.PlanTech.Web.UnitTests/TagHelpers/HeaderTagHelperTests.cs
tests/Dfe.PlanTech.Web.UnitTests/ViewComponents/CategoryLandingViewComponentTests.cs
tests/Dfe.PlanTech.Web.UnitTests/ViewComponents/CategorySectionViewComponentTests.cs
tests/Dfe.PlanTech.Web.UnitTests/ViewComponents/FooterLinksViewComponentTests.cs
tests/Dfe.PlanTech.Web.UnitTests/ViewComponents/GroupsDashboardViewComponentTests.cs

Unit tests for ViewComponents
A couple of additional test fixes (removing usings)

feat: unit tests for Web.ViewComponents

---

tests/Dfe.PlanTech.Web.E2ETests.Beta/features/change-answers.feature
tests/Dfe.PlanTech.Web.E2ETests.Beta/features/check-answers.feature
tests/Dfe.PlanTech.Web.E2ETests.Beta/features/cookies.feature
tests/Dfe.PlanTech.Web.E2ETests.Beta/features/print-recommendations.feature
tests/Dfe.PlanTech.Web.E2ETests.Beta/features/step_definitions/common.steps.ts
tests/Dfe.PlanTech.Web.E2ETests.Beta/features/step_definitions/recommendation-page.steps.ts

Addresses ticket [#220939](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/220939)
Print preview page test and some other test fixes.

test(220939): Print recommendation page test and few additional test fixes

---

src/Dfe.PlanTech.Web/Controllers/GroupsController.cs
src/Dfe.PlanTech.Web/ViewBuilders/GroupsViewBuilder.cs
tests/Dfe.PlanTech.Web.UnitTests/ViewBuilders/GroupsViewBuilderTests.cs

Fixes missing SelectedSchoolUrn cookie issue, redirects to SelectASchool
Unit tests to follow - removed failing test

fix: handle missing groups cookie

---

src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2025/20250905_1200_AddRecommendationTables.sql

Add  **recommendation** and **establishmentRecommendationHistory** table script with relevant FK's

Add  recommendation and establishmentRecommendationHistory scripts

---

.github/actions/run-unit-tests/action.yml

Changes the run-unit-tests GitHub action to remove noise from output

Remove noise from unit test output
