src/Dfe.PlanTech.Domain/Content/Models/MissingComponent.cs
src/Dfe.PlanTech.Infrastructure.Contentful/Persistence/ContentfulRepository.cs
src/Dfe.PlanTech.Infrastructure.Contentful/Persistence/EntityResolver.cs
src/Dfe.PlanTech.Web/Views/Shared/Components/MissingComponent.cshtml
tests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests/Persistence/ContentfulRepositoryTests.cs

**Feature**:
- When an entity is returned from the Contentful API, but is not found locally in code, do not throw an error but return a dummy component instead.
- Logs warning message to logger as well, for debugging/tracking missing components.

feat: Missing component type for non-found entity

---

src/Dfe.PlanTech.Web/Controllers/QuestionsController.cs
tests/Dfe.PlanTech.Web.UnitTests/Controllers/QuestionsControllerTests.cs

- Makes certain actions non-async as modifier was not performing anything currently, but was throwing up warnings as a result.

minor: Make methods non-async

---

src/Dfe.PlanTech.Domain/Content/Interfaces/IRichTextContentPartRenderer.cs
src/Dfe.PlanTech.Domain/Content/Interfaces/IRichTextContentPartRendererCollection.cs
src/Dfe.PlanTech.Domain/Content/Interfaces/IRichTextRenderer.cs
src/Dfe.PlanTech.Domain/Content/Models/Options/TextRendererOptions.cs
src/Dfe.PlanTech.Domain/Dfe.PlanTech.Domain.csproj
src/Dfe.PlanTech.Infrastructure.Contentful/Content/Renderers/Models/PartRenderers/BaseRichTextContentPartRender.cs
src/Dfe.PlanTech.Infrastructure.Contentful/Content/Renderers/Models/PartRenderers/HyperlinkRenderer.cs
src/Dfe.PlanTech.Infrastructure.Contentful/Content/Renderers/Models/PartRenderers/ListItemRenderer.cs
src/Dfe.PlanTech.Infrastructure.Contentful/Content/Renderers/Models/PartRenderers/OrderedListRenderer.cs
src/Dfe.PlanTech.Infrastructure.Contentful/Content/Renderers/Models/PartRenderers/ParagraphRenderer.cs
src/Dfe.PlanTech.Infrastructure.Contentful/Content/Renderers/Models/PartRenderers/UnorderedListRenderer.cs
src/Dfe.PlanTech.Infrastructure.Contentful/Content/Renderers/Models/RichTextRenderer.cs
src/Dfe.PlanTech.Infrastructure.Contentful/Dfe.PlanTech.Infrastructure.Contentful.csproj
src/Dfe.PlanTech.Web/Program.cs
src/Dfe.PlanTech.Web/TagHelpers/RichText/RichTextTagHelper.cs
tests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests/Content/Renderers/Models/PartRenderers/HyperlinkRendererTests.cs
tests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests/Content/Renderers/Models/PartRenderers/ListItemRendererTests.cs
tests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests/Content/Renderers/Models/PartRenderers/OrderedListRendererTests.cs
tests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests/Content/Renderers/Models/PartRenderers/ParagraphRendererTests.cs
tests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests/Content/Renderers/Models/PartRenderers/TextRendererTests.cs
tests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests/Content/Renderers/Models/PartRenderers/UnorderedListRendererTests.cs
tests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests/Content/Renderers/Models/RichTextRendererTests.cs

- Refactors Rich Text renderers slighty; children renderering handled by `IRichTextContentPartRendererCollection` only
- Adds `ILogger` to RichTextRendererer
- Adds logging for various warnings/errors
- Missing renderer for rich text
- Missing mark for text body

feat: Add logging to Rich Text content renderers

---

src/Dfe.PlanTech.Application/Caching/Interfaces/IUrlHistory.cs
src/Dfe.PlanTech.Application/Caching/Models/UrlHistory.cs
src/Dfe.PlanTech.Web/Controllers/QuestionsController.cs
src/Dfe.PlanTech.Web/ProgramExtensions.cs
tests/Dfe.PlanTech.Application.UnitTests/Core/UrlHistoryTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Controllers/QuestionsControllerTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Middleware/UrlHistoryMiddlewareTests.cs

- Moves UrlHistory class + interfaces to a different folder

refactor: Move UrlHistory to /Caching/ folder

---

src/Dfe.PlanTech.Application/Caching/Interfaces/IQuestionnaireCacher.cs
src/Dfe.PlanTech.Application/Caching/Models/QuestionnaireCacher.cs
src/Dfe.PlanTech.Application/Content/Queries/GetPageQuery.cs
src/Dfe.PlanTech.Application/Questionnaire/Queries/GetQuestionQuery.cs
src/Dfe.PlanTech.Domain/Caching/Interfaces/IQuestionnaireCache.cs
src/Dfe.PlanTech.Domain/Caching/Models/QuestionnaireCache.cs
src/Dfe.PlanTech.Domain/Content/Models/Page.cs
src/Dfe.PlanTech.Web/Controllers/QuestionsController.cs
src/Dfe.PlanTech.Web/ProgramExtensions.cs
src/Dfe.PlanTech.Web/Views/Pages/Page.cshtml
src/Dfe.PlanTech.Web/Views/Shared/Questionnaire/Category.cshtml
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetPageQueryTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Controllers/PagesControllerTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Controllers/QuestionsControllerTests.cs

- Adds caching for questionnaire data
- Currently just `Current Section Title`
- Uses caching to display the current section title on the `Check your answers` page
- Routes to proper check your answers page
- Note: This will need improving. Needs content model changes. To be dealt with on another ticket.

feat: Add section title

---

src/Dfe.PlanTech.Web/Program.cs

- Amends KeyVault configuration to only run in production mode
Using KeyVault locally leads to problems as it requires adding the Keyvault name in your configuration, as well as obviously logging into Azure.
This is not the main issue, as even if this is done, due to the URL re-writes used for DFE SignIn, it means that the callback URLs for signin lead to the _dev environment_. I.e. you will be re-directed back to https://dev-plantech.com/auth/cb instead of https://localhost:1234/auth/cb.
By making the KV run in production _only_, this will ensure minimise issues caused by the above.

fix: Add production check for keyvault

---

.github/workflows/sonar-cloud.yml
.github/workflows/terraform-pr-check.yml
src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2023/20230724_1439_CreateDataProtectionTable.sql
src/Dfe.PlanTech.Infrastructure.Data/DataProtectionDbContext.cs
src/Dfe.PlanTech.Infrastructure.Data/Dfe.PlanTech.Infrastructure.Data.csproj
src/Dfe.PlanTech.Web/Dfe.PlanTech.Web.csproj
src/Dfe.PlanTech.Web/Program.cs
terraform/key-vault.tf
terraform/variables.tf

Fixes 405 error - ticket [170087](https://dev.azure.com/dfe-ssp/s190-schools-technology-services/_sprints/taskboard/Plan%20Tech/s190-schools-technology-services/Plan%20Tech/Plan%20Tech%20sprint%207?workitem=170087)
- Adds storage of Data Protection keys in database
- Adds key for above in Azure Keyvault
- Updates Terraform to generate KV Key for above
- Adds `Program.cs` to coverage exclusions for SonarCloud

feat: Add Data Protection Storage

---

.github/workflows/sonar-cloud.yml

- Rename job to be more descriptive
- Remove JDK step
- Add `path` restriction for PR

chore: SonarCloud workflow tweaks

---

src/Dfe.PlanTech.Web/Dockerfile
src/Dfe.PlanTech.Web/appsettings.json
terraform/main-hosting.tf

- Reverts Docker port back to 8080, due to port 80 still not working
- Adds port into Terraform

fix: Revert Docker port

---

src/Dfe.PlanTech.Web/Controllers/BaseController.cs
src/Dfe.PlanTech.Web/Controllers/PagesController.cs
src/Dfe.PlanTech.Web/Views/Shared/Error.cshtml
tests/Dfe.PlanTech.Web.UnitTests/Controllers/PagesControllerTests.cs

- Moves error page handling route from `BaseController` to `PagesController`
- Fixes issue where multiple routes of `/Error` were being registered as a result

fix: Move error route to prevent duplicate routes

---

.github/workflows/code-pr-check.yml

Amends the triggers on the `code-pr-check.yml` workflow to only trigger when changes have been made in the `src` or `tests` folder.

feat: Amend code PR check to only trigger on changes to src or tests

---

.github/workflows/matrix-deploy.yml

- Limits app deployments to code changes only. Prevents having a ton of deployments when there have been 0 actual changes to deploy.

cicd: Restrict deployments to code changes

---

docs/adr/0027-accesibility-testing.md
docs/adr/README.md
src/Dfe.PlanTech.Web/Controllers/PagesController.cs
src/Dfe.PlanTech.Web/Views/Shared/_Layout.cshtml
tests/Dfe.PlanTech.Web.E2ETests/README.md
tests/Dfe.PlanTech.Web.E2ETests/cypress.config.js
tests/Dfe.PlanTech.Web.E2ETests/cypress.env.json.example
tests/Dfe.PlanTech.Web.E2ETests/cypress/commands/axe-tools.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/commands/login.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/interstitial-page.cy.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/landing-page.cy.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/question-page.cy.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/self-assessment.cy.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/support/commands.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/support/e2e.js
tests/Dfe.PlanTech.Web.E2ETests/package-lock.json
tests/Dfe.PlanTech.Web.E2ETests/package.json

- Adds accessibility checks in our E2E testing using axe via [cypress-axe](https://www.npmjs.com/package/cypress-axe)
- Adds a title to each page to pass an accessibility issue
- Adds ADR for the above
*Note*: The title for each page is expected to change, along with the functionality that creates it.

feat: add axe tools to cypress

---

src/Dfe.PlanTech.Web/Program.cs

- Removes unnecessary `MapControllerRoute` calls
- Removes duplicate `UseCookiePolicy` call

refactor: Remove unnecessary lines from program.cs

---

src/Dfe.PlanTech.Web/Controllers/PagesController.cs
src/Dfe.PlanTech.Web/Helpers/GtmConfiguration.cs
src/Dfe.PlanTech.Web/Models/PageViewModel.cs
src/Dfe.PlanTech.Web/Program.cs
src/Dfe.PlanTech.Web/ProgramExtensions.cs
src/Dfe.PlanTech.Web/Views/Pages/Page.cshtml
src/Dfe.PlanTech.Web/Views/Shared/_Layout.cshtml
tests/Dfe.PlanTech.Web.UnitTests/Controllers/PagesControllerTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Helpers/GtmConfigurationTests.cs

- Moves GTM code around so that it is added in `_Layout.cshtml`, not `Page.cshtml`
- The latter is not used for every page, meaning a large majority of pages did not actually include the GTM code

fix: Google Tag Manager

---

src/Dfe.PlanTech.Application/Submission/Commands/CreateSubmissionCommand.cs
src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2023/20230913_1224_UpdateSubmissionNullability.sql
src/Dfe.PlanTech.Domain/Submissions/Models/Submission.cs
tests/Dfe.PlanTech.Application.UnitTests/Submission/Queries/GetSubmissionQueryTest.cs
tests/Dfe.PlanTech.Web.UnitTests/Controllers/QuestionsControllerTests.cs

Makes the following columns nullable in `submission` table:
- `submissionId`
- `submissionName`
Drops the following unused column in the same table:
- `recommendationId`
- Removes all references to the latter across code (only self-referential, or used in tests)
- Cleans up Questions Controller Tests file

feat: Fix nullability in schema

---

src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2023/20230913_1224_UpdateSubmissionNullability.sql

- Fixes column naming to match (misspelled) existing column name

fix: Spelling in SQL Script

---

src/Dfe.PlanTech.Web/Views/CheckAnswers/CheckAnswers.cshtml
tests/Dfe.PlanTech.Web.E2ETests/cypress/commands/question-page.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/accessibility-page.cy.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/check-answer-page.cy.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/privacy-policy-page.cy.js

- Re-adds some missing attributes on `Change` links on the `Check Answers` page that had been removed accidentally in recent work.
- Removes a few tests that should be unnecessary, to reduce test run time
- Adds another test for Check Answers page, that checks:
- Every chosen question + answer exists on the Check Answers page
- Each has a "Change" link
- Each link has an `aria-label` and a `title` attribute with the correct expected values

fix: Missing attributes on check answers page

---

src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2023/20230816_132200_CreateAnalyticsUser.sql
src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2023/20230921_1150_DeleteAnalyticsUser.sql

As we've moved to Azure AD auth for the SQL server, this user is no longer necessary.
- Removes script that creates user
- Adds a script that drops the user from the DB if exists
Note: I've inlined the user username as:
1. It should no longer be a security issue, since it will be deleted
2. Otherwise we'll need to keep the secret for the username in GitHub indefinitely; inlining it allows us to clear it out.

feat: Remove SQL Analytics User

---

.github/workflows/code-pr-check.yml
.github/workflows/e2e-tests.yml

- Changes build workflows back to using Ubuntu, not Windows, again. 
- This time targeting a specific, older version (20.04), which fixes the bug with the newer versions.
- End result is the unit + E2E testing workflows having their run time halved.

feat: Change workflows to use Ubuntu again

---

.github/actions/run-e2e-tests/action.yml
.github/workflows/deploy-image.yml
.github/workflows/matrix-deploy.yml

This PR is part of the resolution to fix the environment referencing issue.
We now know that the workflow is referencing the repository secret instead of the environment secret specifically for the "Cypress Testing" stage, but not for the rest of the steps even within the same job.

feature/184003 - Resolve E2E Test Environment Issue

---

.github/workflows/build-image.yml
.github/workflows/deploy-image.yml
.github/workflows/matrix-deploy.yml

This PR adds in two missing steps from the deployment pipeline (upgrade database in \<ENV> and create/tag release).
This PR also tweaks the pipeline by changing the image tags from `latest-<ENV>` to `<TARGET_BRANCH>-<SHA>-<ENV>` for the Azure Container Registry, and `latest` to `<TARGET_BRANCH>-<SHA>` for the Github Container Registry. This will ensure a greater separation of concerns when deploying to either development or main and gives us more information at face-value to verify images are being created and deployed properly to their relevant environments.

refactor - Tweak Pipeline

---

src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2023/20231206_1457_CreateCmsDbSchemas.sql
src/Dfe.PlanTech.Domain/Content/Models/ComponentDropDownDbEntity.cs
src/Dfe.PlanTech.Domain/Content/Models/PageContentDbEntity.cs
src/Dfe.PlanTech.Domain/Content/Models/RichTextContentDbEntity.cs
src/Dfe.PlanTech.Domain/Content/Models/TextBodyDbEntity.cs
src/Dfe.PlanTech.Infrastructure.Data/CmsDbContext.cs

Minor changes to the SQL table schemas:
- Fixes missing Page -> Content relationship
- Adds foreign key field to DropDown class for the RichText content, and renames the actual foreign key due to name already in use
- Fixes warning -> textbody relationship not working
- Updates SQL script

fix: Caching SQL Table fixes

---

src/Dfe.PlanTech.AzureFunctions/Mappings/ButtonDbMapper.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/ButtonWithEntryReferenceMapper.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/ButtonWithLinkMapper.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/CategoryMapper.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/JsonToDbMapper.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/QuestionMapper.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/RecommendationPageMapper.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/SectionMapper.cs
src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2023/20231206_1457_CreateCmsDbSchemas.sql
src/Dfe.PlanTech.Domain/Content/Models/Buttons/ButtonDbEntity.cs
src/Dfe.PlanTech.Domain/Content/Models/Buttons/ButtonWithEntryReferenceDbEntity.cs
src/Dfe.PlanTech.Domain/Content/Models/Buttons/ButtonWithLinkDbEntity.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/CategoryDbEntity.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationPageDbEntity.cs
src/Dfe.PlanTech.Infrastructure.Data/CmsDbContext.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/AnswerMapperTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/BaseMapperTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/ButtonMapperTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/ButtonWithEntryReferenceMapperTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/ButtonWithLinkMapperTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/CategoryMapperTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/JsonToDbMapperUnitTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/QuestionMapperTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/RecommendationPageMapperTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/SectionMapperTests.cs

**Features**:
Adds remaining mappers for Contentful -> Db:
- Buttons
- Category
- RecommendationPage
- Section
**Minor changes**:
- Rename a column in table to match the other's naming convention
- Refactor a couple methods
- Add a missing field for relationship

feat: Add remaining caching mappers

---

.github/workflows/build-and-deploy-azure-function.yml
.github/workflows/matrix-deploy.yml
.github/workflows/validate-scripts.yml

The Matrix Build & Deploy for [PR 307](https://github.com/DFE-Digital/plan-technology-for-your-school/actions/runs/7248765753) is skipping jobs unexpectedly, this PR is for implementing a fix.
Also adds a wait timer to the `validate-scripts.yml` pipeline, as this should ensure the Docker daemon for the SQL server has started up before DbUpgrader runs on it. Could be replaced with a more sophisticated wait method in the future but would be complex.

Fix Pipeline Skipping Issue

---

src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2024/20240109_1124_CreateMissingIndexesAndRelationships.sql
terraform/container-app/terraform-configuration.md

Adds missing foreign keys for certain tables to `ContentComponent` table. 
- `Buttons`
- `ComponentDropdowns`
- `Headers`
- `InsetTexts`
- `NavigationLink`

fix: Add missing FKs and indexes

---

src/Dfe.PlanTech.Application/Content/Queries/GetPageQuery.cs
src/Dfe.PlanTech.Application/Persistence/Interfaces/ICmsDbContext.cs
src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2024/20240111_0919_CreateAllRichTextContentForPageSlugFunction.sql
src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2024/20240111_0926_DropOldFunctionAndType.sql
src/Dfe.PlanTech.Domain/Content/Interfaces/IHasRichText.cs
src/Dfe.PlanTech.Domain/Content/Models/WarningComponentDbEntity.cs
src/Dfe.PlanTech.Infrastructure.Data/CmsDbContext.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetPageQueryTests.cs

A bug was added from the recent caching feature being added.
The query that retrieved rich text content for TextBody components was caching every query as just one (i.e. it didn't matter if the query was for a different bunch of TextBodys or not, it was all treated as the same query). As a result, RichText was not loaded/displayed correctly for the majority of pages once you navigated through.

fix: Missing rich texts

---

src/Dfe.PlanTech.AzureFunctions/Functions/QueueReceiver.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/AsyncEnumerable.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/AsyncEnumerator.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/AsyncQueryProvider.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Functions/QueueReceiverTests.cs

Due to changes in the CmsDbContext, relationship data was being pulled in when `_db.Find` was being executed.
As a result, when the additional relationship mapping was occurring, it appeared that we wanted to do things such as delete all the existing rows.
This PR changes the logic to ensure that AutoIncludes are disabled.

fix: Ignore autoincludes in find query

---

src/Dfe.PlanTech.Application/Constants/UrlConstants.cs
src/Dfe.PlanTech.Web/Middleware/ServiceExceptionHandlerMiddleWare.cs
tests/Dfe.PlanTech.Web.UnitTests/Middleware/ServiceExceptionHandlerMiddlewareTests.cs

- added single error page for organisation and service errors. Could be temporary if DSI team fix their issue around the data

feat/189212 - Single error page

---

src/Dfe.PlanTech.Web/appsettings.json

Huge amount of logs going on due to the log level being set at "Information", so this changes it to be "Warning" by default.
Note: We can change this per environment, whenever wanted, by changing the environment variables on the containers, or setting values in the Azure KeyVault.

fix: Set default log level to warning

---

src/Dfe.PlanTech.Web/ViewComponents/CategorySectionViewComponent.cs
tests/Dfe.PlanTech.Web.UnitTests/ViewComponents/CategorySectionViewComponentTests.cs

- Adds logging when a category has no sections, instead of just redirecting to service unavailable page.
- Also drops out of method earlier, as no reason to attempt to collection section statuses for a category that has no sections

feat: Add logging for missing sections

---

src/Dfe.PlanTech.Application/Content/Queries/GetButtonWithEntryReferencesQuery.cs
src/Dfe.PlanTech.Application/Content/Queries/GetCategorySectionsQuery.cs
src/Dfe.PlanTech.Application/Content/Queries/GetPageQuery.cs
src/Dfe.PlanTech.Application/Content/Queries/GetRichTextsQuery.cs
src/Dfe.PlanTech.Application/Helpers/QueryServiceSetup.cs
src/Dfe.PlanTech.Domain/Content/Interfaces/IGetNavigationQuery.cs
src/Dfe.PlanTech.Domain/Content/Interfaces/IGetPageChildrenQuery.cs
src/Dfe.PlanTech.Domain/Content/Interfaces/IGetPageQuery.cs
src/Dfe.PlanTech.Web/Authorisation/PageModelAuthorisationPolicy.cs
src/Dfe.PlanTech.Web/Routing/CheckAnswersRouter.cs
src/Dfe.PlanTech.Web/Routing/GetRecommendationRouter.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetButtonWithEntryReferencesQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetCategorySectionsQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetPageQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetRichTextsQueryTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Authorisation/PageModelAuthorisationPolicyTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Controllers/CookieControllerTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Routing/CheckAnswersRouterTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Routing/GetRecommendationRouterTests.cs

Split up queries from GetPageQueries into separate classes.
Was becoming a pain trying to update and/or test them due to the size of the GetPageQuery class in the end.

refactor: Split page queries

---

tests/Dfe.PlanTech.AzureFunctions.UnitTests/Functions/QueueReceiverTests.cs

Adds some small improvements to QueueReceiver tests to ensure certain things work as expected.
1. Ensures that the archive/unarchive/delete/etc. logic works and sets the relevant field to the expected value.
2. Ensures that the logic to find an existing entity from the DB works as expected
3. Ensures that the `Add` method is called if an entity is a new entity
4. Ensures that the new entity has the Id field set.
There's probably more tests/changes to come around this to make it more robust, but for now I believe this covers the important things.

tests: Improve QueueReceiver tests

---

tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetNavigationQueryTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/AsyncQueryProvider.cs
tests/Dfe.PlanTech.Infrastructure.SignIn.UnitTests/DfeOpenIdConnectEventsTests.cs

- Reenables a unit test in `DfeOpenIdConnectEventTests`
- This was already running technically but no functionality tested. 
- Functionality is independent of whether we actually use this logic in web app or not; should be tested.
- Changes methods in `GetNavigationQueryTests` to use correct method (`Throws` instead of `Returns`) to remove warnings
- Ignore nullability warnings in `AsyncQueryProvider` to remove warnings

tests: Minor test changes

---

src/Dfe.PlanTech.Web/ViewComponents/CategorySectionViewComponent.cs

- Makes the error for a missing interstital page the same as if the slug was null
- Removes `ref` keyword in places it was used in the same file as unnecessary

fix: make error handling consistent

---

src/Dfe.PlanTech.AzureFunctions/Functions/QueueReceiver.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/JsonToDbMapper.cs
src/Dfe.PlanTech.Domain/Caching/Enums/CmsEvent.cs
src/Dfe.PlanTech.Infrastructure.Data/CmsDbContext.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Functions/QueueReceiverTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/BaseMapperTests.cs

Ticket: [190555](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_boards/board/t/Plan%20Tech/Stories/?workitem=190555)
This ticket adds a global filter to all queries from the CMS DB that only allows content that is published, not archived and not deleted to be pulled in when using the service.
It also fixes a special case regarding unpublishing content where a special "DeletedEntry" JSON needs to be parsed, which includes a rejigging of QueueReceiver to make it more maintainable.

feat/190555 - Process Published/Archived/Deleted Flags For Content From DB

---

terraform/container-app/functions.tf
terraform/container-app/terraform-configuration.md
terraform/container-app/versions.tf

- Adds the KV reference identity ID to function app in Terraform
- Updates `azurerm` provider version to earliest one that supports .NET 8 in function apps.

fix: add KV reference identity id

---

src/Dfe.PlanTech.AzureFunctions/Functions/QueueReceiver.cs
src/Dfe.PlanTech.AzureFunctions/Startup.cs
src/Dfe.PlanTech.Domain/Content/Models/ContentComponentDbEntity.cs
src/Dfe.PlanTech.Domain/Persistence/Models/ContentfulOptions.cs
src/Dfe.PlanTech.Infrastructure.Data/CmsDbContext.cs
src/Dfe.PlanTech.Web/ProgramExtensions.cs
src/Dfe.PlanTech.Web/appsettings.json
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Functions/QueueReceiverTests.cs

- Adds ContentfulOptions class to get "UsePreview" variable in Azure Function, Web Project, and DB project
- If "UsePreview" is true:
- In Azure functions: Ignore "Save" and "Auto save" events
- In DB: allow "unpublished" content to be retrieved

feat: Support preview mode in Content db

---

src/Dfe.PlanTech.Infrastructure.Data/CmsDbContext.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Functions/QueueReceiverTests.cs

Fixes problems with Azure Function tests caused by removing parameterless constructor in CmsDbContext

fix: Azure Function Tests

---

src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2024/20240209_1448_FixSelectAllRichTextContentForPageSlugFunction.sql

- Fixes types in `@RichTextIds` and `idColumn`
- Optimised the querying of the fetching of the `ContentComponentIds` and the `RichTextIds`

fix: RichText retrieval bug

---

.github/workflows/code-pr-check.yml

SonarCloud has some hard dependencies with `dotnet-coverage 17.9.3`, updating it caused the coverage to always report as 0%, this PR rolls back the update to fix it.

fix: SonarCloud Coverage

---

.github/workflows/code-pr-check.yml
src/Dfe.PlanTech.AzureFunctions/Functions/QueueReceiver.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Functions/QueueReceiverTests.cs

Ticket: [195442](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_boards/board/t/Plan%20Tech/Stories/?workitem=195442)
This PR addresses the comments left in https://github.com/DFE-Digital/plan-technology-for-your-school/pull/491
References to commit hashes in this PR have been left in the comments in #491
Specifically it:
- Merges ShouldDropMessage and ShouldIgnoreMessage into one function for less confusion.
- In the event of an invalid component, logs out exactly which properties are invalid.
- Checks to see if the incoming entity is valid regardless of whether a version exists or not in the Db already, as anything missing means it was a required field in Contentful that was deleted.

refactor/195442 - PR #491 Tech Debt

---

src/Dfe.PlanTech.Application/Submissions/Queries/GetSubmissionStatusesQuery.cs
src/Dfe.PlanTech.Domain/Interfaces/IGetSubmissionStatusesQuery.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/Category.cs
src/Dfe.PlanTech.Web/TagHelpers/TaskList/TagColour.cs
src/Dfe.PlanTech.Web/TagHelpers/TaskList/TaskListTagTagHelper.cs
src/Dfe.PlanTech.Web/ViewComponents/CategorySectionViewComponent.cs
src/Dfe.PlanTech.Web/ViewComponents/RecommendationsViewComponent.cs
tests/Dfe.PlanTech.Application.UnitTests/Submissions/Queries/GetSubmissionStatusesQueryTests.cs
tests/Dfe.PlanTech.Web.UnitTests/TagHelpers/TaskListTagTagHelperTests.cs
tests/Dfe.PlanTech.Web.UnitTests/ViewComponents/CategorySectionViewComponentTests.cs
tests/Dfe.PlanTech.Web.UnitTests/ViewComponents/RecommendationsViewComponentTests.cs

- In [version 5](https://github.com/alphagov/govuk-design-system-backlog/issues/62#issuecomment-1888918535) of the GDS front-end packages, they have changed the tag colours. As a result, our "dark blue" tag no longer existed, so all of our tags were using the default colours.
- Changed tag colours to match changes.
- Change return type to list; improves performance by not having to call `.ToList` on an object that is already a List
- Make async

:zap:: Update Category + Recommendation View Components

---

src/Dfe.PlanTech.Domain/Questionnaire/Interfaces/IRecommendationChunk.cs
src/Dfe.PlanTech.Domain/Questionnaire/Interfaces/IRecommendationIntro.cs
src/Dfe.PlanTech.Domain/Questionnaire/Interfaces/IRecommendationSection.cs
src/Dfe.PlanTech.Domain/Questionnaire/Interfaces/ISubTopicRecommendation.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationChunk.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationIntro.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationSection.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/SubTopicRecommendation.cs
tests/Dfe.PlanTech.Application.UnitTests/Questionnaire/Queries/RecommendationComponentTests.cs

This PR creates the C# entities for mapping the new recommendation content from Contentful
Tickets:
- [196687](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_boards/board/t/Plan%20Tech/Stories/?workitem=196687)
- [196688](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_boards/board/t/Plan%20Tech/Stories/?workitem=196688)
- [196689](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_boards/board/t/Plan%20Tech/Stories/?workitem=196689)
- [196690](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_boards/board/t/Plan%20Tech/Stories/?workitem=196690)
**TODO**

refactor: Contentful Models

---

src/Dfe.PlanTech.Web/Views/Shared/_Layout.cshtml

E2E tests appear to be failing due to the step-by-step navigation.
As the accordion has been removed, the script to initialise it was failing as it was unable to find the right elements.
When we have the recommendation page proper (or wherever the accordion might be used), we should add the JS back in to that page specifically.
```
<script src="/js/step-by-step-navigation.js"></script>
<script src="/js/step-by-step-polyfills.js"></script>
<script type="module">
var $element = document.querySelector('#step-by-step-navigation')
var stepByStepNavigation = new GOVUK.Modules.AppStepNav($element).init()
</script>
```
As you can see the initialise script attempts to find the the relevant element by ID and then run some JS on it to initialise it. Given that the element doesn't exist the JS fails. …

fix: remove step-by-step navigation js from layout

---

src/Dfe.PlanTech.Web/Views/Shared/_Layout.cshtml

Removed this yesterday in an erroneous attempt to fix the E2E tests. It's necessary for the GOV UK front-end initialisation script though so I've added back in.

chore: Add GovUK body class script in

---

.github/scripts/clear-user-data-from-db.sql
.github/workflows/clear-user-data-from-db.yml

- For some reason the 'Go' commands weren't working from the workflow (although worked directly on DB). Removed.
- Tweaked CI/CD pipeline a bit to ensure safety
Should now also be able to run it from `Actions` tab as the workflow should show there.
Can also run manually using the GitHub CLI. E.g.
`gh workflow run 'Clear user data from DB' --ref development -f environment=development`

💚 Fix SQL script to clear DB

---

tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/self-assessment.cy.js

Removes a specific text/content check from the Self-Assessment E2E tests, as the content has/might change which has caused the test to fail.

fix: :white_check_mark: remove text match check

---

src/Dfe.PlanTech.Application/Content/Queries/GetSubTopicRecommendationFromContentfulQuery.cs
src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2024/20240321_1003_AlterRichTextContentsWithSubtopicRecommendationIdView.sql
src/Dfe.PlanTech.Infrastructure.Data/Repositories/RecommendationsRepository.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetSubTopicRecommendationFromContentfulQueryTests.cs

- Fixes issue where query for Recommendations on the self-assessment page was failing from Contentful.  [^1]
- Retrieves `Title` for RecommendationChunk from DB
- Renames column in SQL view to ensure complete DB query works.
[^1]: This was caused by me trying to filter the request down by the intro maturity, and Contentful didn't like it. This could have been fixed, however it would never have had the intended result anyway, so I have just removed it.

fix(recommendations): :bug: Recommendations querying

---

src/Dfe.PlanTech.AzureFunctions/Functions/QueueReceiver.cs
src/Dfe.PlanTech.Domain/Extensions/StringHelpers.cs

Description on message has a max character length of _4096_. Stacktraces can easily go over that, meaning that the messages were not dead lettered.
Closes #201678

fix(functions): :bug: Truncate deadletter description length

---

.github/workflows/code-pr-check.yml
src/Dfe.PlanTech.DatabaseUpgrader/DatabaseExecutor.cs
src/Dfe.PlanTech.DatabaseUpgrader/Logger.cs
src/Dfe.PlanTech.DatabaseUpgrader/Options.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetCategorySectionsQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetSubTopicRecommendationFromContentfulQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetSubTopicRecommendationFromDbQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetSubTopicRecommendationQueryTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/RecommendationChunkMapperTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/RecommendationChunkUpdaterTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/RecommendationIntroMapperTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/RecommendationSectionMapperTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/RecommendationSectionUpdaterTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/SubtopicRecommendationMapperTests.cs
tests/Dfe.PlanTech.Infrastructure.Data.UnitTests/Repositories/RecommendationsRepositoryTests.cs

- Adds check permissions to linting job so that it works
- Removes the job matrix, and just lint the entire `./src` directory anyway [^1]
[^1]: Originally the job would get every directory within the `src` folder, and then lint them all individually one by one. This seems unnecessary, and takes a lot longer (as we have to checkout each time, then install .NET, etc.). This should make it a lot quicker.

fix: Give checks permission to linting job + improve performance

---

docs/adr/0036-db-unit-tests.md
src/Dfe.PlanTech.AzureFunctions/Mappings/PageEntityRetriever.cs
src/Dfe.PlanTech.AzureFunctions/Utils/MessageRetryHandler.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/AsyncQueryProvider.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Dfe.PlanTech.AzureFunctions.UnitTests.csproj
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/PageEntityRetrieverTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/PageMapperTests.cs

The existing page query resulted in a **massive** SQL query which often timed out, especially on more complex pages.
Whilst this has been fixed in various other places (e.g. the web app page query), it was missed from the Azure Function.
The redelivery message task was not awaited, meaning that redelivery might have not happened by the time the parent methods exits.
This fix awaits the redeliver message method.

fix(functions): :ambulance: Page query + redelivery handler

---

src/Dfe.PlanTech.AzureFunctions/Functions/QueueReceiver.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/EntityUpdater.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/PageEntityRetriever.cs
src/Dfe.PlanTech.AzureFunctions/Mappings/PageEntityUpdater.cs
src/Dfe.PlanTech.AzureFunctions/Models/MappedEntity.cs
src/Dfe.PlanTech.Infrastructure.Data/CmsDbContext.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Functions/QueueReceiverTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/PageEntityUpdaterTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Utils/MessageRetryHandlerTests.cs

1. Retrieve the `Id` column for the `PageContents` table joins when retrieving the existing page from the DB
- The lack of this was causing the code that removed duplicate content to fail (hard to delete something without the PK).
2. Don't use the specific `Content` and `BeforeTitleContent` fields in the existing entity when doing any mapping; just amend the `AllPageContent` field.
- This was causing errors as EF Core was assuming that these fields + AllPageContents had different copies of the same data.
1. Don't bother with extra mapping when processing an `UNPUBLISH` or `DELETE` event.
- Shouldn't fix anything, but should just slightly speed up these events, and reduce any chances of errors.
- This could be further improved by not even bothering to retrieve the existing entity for these …

fix(functions): :ambulance: Page content changes - 206886

---

src/Dfe.PlanTech.AzureFunctions/host.json

Removes the `Server` header that was previously showing Kestral
Adds the following headers that were identified as missing 
- Strict-Transport-Security
- Content-Security-Policy
- X-Frame-Options
- Cache-Control
- Content-Type
- X-XSS-Protection
- X-Content-Type-Options

fix(functions): Configure Api security headers

---

src/Dfe.PlanTech.Web/README.md

Add a link to the sign in secrets to ensure this isn't missed during setup

docs(setup): Add Link to SignIn secrets in setup readme

---

contentful/export-processor/data-tools.js

Puts outputted files in another subdirectory named after the Contentful environment.
Allows you (read: me) to run against multiple environments repeatedly without overwriting local data all the time.

feat(contentful-processor): :sparkles: Add Contentful environment to output directory

---

.github/workflows/terraform-plan.yml
terraform/container-app/locals.tf
terraform/container-app/main-hosting.tf
terraform/container-app/terraform-configuration.md
terraform/container-app/user-assigned-identity.tf
terraform/container-app/variables.tf

- Adds variable options to Terraform for scaling the container app
- Minimum replicas
- Maximum replicas
- HTTP Concurrency
- Updates CI/CD pipeline to add new variables if existing as secrets.
- Removes an unused MI that was accidentally added in with the recent update Terraform PR

feat(iac): Add scaling options for container app to Terraform

---

terraform/container-app/functions.tf
terraform/container-app/main-hosting.tf

- Sets `storage_account_access_key` setting in the Azure Function App if `local.container_app_storage_account_shared_access_key_enabled` is enabled.
- Actually use the MSSQL SKU from previous PR

fix(tf): Set storage access key + SQL SKU

---

src/Dfe.PlanTech.Application/Submissions/Queries/GetSubmissionStatusesQuery.cs
src/Dfe.PlanTech.Application/Submissions/Queries/SubmissionStatusProcessor.cs
src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2024/20240605_1030_UpdateGetSectionStatusesSproc.sql
src/Dfe.PlanTech.Domain/Interfaces/IGetSubmissionStatusesQuery.cs
src/Dfe.PlanTech.Domain/Submissions/Interfaces/ISubmissionStatusProcessor.cs
src/Dfe.PlanTech.Domain/Submissions/Models/SectionStatus.cs
src/Dfe.PlanTech.Web/Routing/GetRecommendationRouter.cs
src/Dfe.PlanTech.Web/ViewComponents/RecommendationsViewComponent.cs
tests/Dfe.PlanTech.Application.UnitTests/Submissions/Queries/GetSubmissionStatusesQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Submissions/Queries/SubmissionStatusProcessorTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Routing/GetRecommendationRouterTests.cs
tests/Dfe.PlanTech.Web.UnitTests/ViewComponents/RecommendationsViewComponentTests.cs

This PR changes the self-assessment page to always show the most recent recommendation rather than it disappearing if a user restarts a topic and leaves it incomplete
This is done by changing the `GetSectionStatuses` SP to use the maturity from the most recent _complete_ submission, but leaving the completed state as is so the tag shown is correct
implemented by commit 1
This alone doesn't work as if you click on the recommendation link, the journey status processing is shared by Question answers/ Validation of recommendation route. So it just takes you to the incomplete topic
To workaround this a complete flag has been added to the functions that fetch the current status, to allow limiting to complete ones, and using this flag in the context of recommendations
implemented by commit 2

Feat: Show latest recommendation for restarted topics

---

src/Dfe.PlanTech.Web/Views/Shared/_Header.cshtml

**Description**
Removing this button, as it shows up on smaller screens but does nothing, which is likely to be confusing.

Fix: Remove redundant button

---

src/Dfe.PlanTech.Application/Mappings/MappingProfile.cs
src/Dfe.PlanTech.Web/Controllers/QuestionsController.cs
src/Dfe.PlanTech.Web/Helpers/LogInvalidModelState.cs
tests/Dfe.PlanTech.Web.UnitTests/Helpers/LogInvalidModelStateTests.cs

1. Improve the logging message by displaying whole controller method rather than route name (which is often null)
2. Fix the mapping of PageDbEntity -> Page so that the logging stops happening when pages are fetched from the db
3. Remove logging from the check answers endpoint as this already checks state
4. Tests

Fix page mapping and logs

---

src/Dfe.PlanTech.Infrastructure.SignIn/DfeOpenIdConnectEvents.cs
tests/Dfe.PlanTech.Infrastructure.SignIn.UnitTests/DfeOpenIdConnectEventsTests.cs

- Use the `x-forward-host` header (if available) for redirect URI to DSI

fix(dsi): Use x-forward-host header if available

---

tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/QuestionMapperTests.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Mappers/SectionMapperTests.cs

Although `NSubstitute.RecievedWithAnyArgs` states that it checks a substitute has recieved a set number of calls, it isn't actually doing that, voiding the test, and Sonar cloud flagged this up. 
Swapped to asserting a single received call which does work, and fixed test accordingly

Fix test assertions

---

src/Dfe.PlanTech.AzureFunctions/Dfe_PlanTech_AzureFunctions.csproj
src/Dfe.PlanTech.Web/Dfe.PlanTech.Web.csproj

There is a [vulnerability in version 1.11.0](https://github.com/advisories/GHSA-m5vv-6r4h-3vj9)

chore: Update Azure Identity to 1.11.4

---

terraform/container-app/terraform-configuration.md
terraform/container-app/versions.tf

- Update TF docs to match latest AzureRM provider version
- Use specific version of AzureRM provider (3.110.0)[^1]
[^1]: Since we never tied it to a _specific_ version, and just `>=` a version, anytime there was an update our dev -> main process would fail (as the TF docs needed updating, but it couldn't save changes to dev due to protection rules. By tying it to a specific version, we'll ensure this doesn't happen again.

fix(TF): Update TF docs + use specific AzureRM version

---

src/Dfe.PlanTech.Domain/Content/Enums/RichTextNodeType.cs
src/Dfe.PlanTech.Domain/Content/Interfaces/IRichTextContent.cs
src/Dfe.PlanTech.Infrastructure.Contentful/Content/Renderers/Models/PartRenderers/HeadingRenderer.cs
tests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests/Content/Renderers/Models/PartRenderers/HeadingRendererTests.cs

Adds support for rendering headers within Rich content. 
The h1-h6 tags use the dfe classes which are all sized to line up with the XL/L/M/S ones so left as is.

Feat: Support headings in rich text

---

src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2024/20240717_1510_AlterSectionStatusesProc.sql

This fixes an edge case where if you:
- Answer all questions in a topic and wait at the check answers page for a few minutes
- Then press save and continue
The "Last completed" time is the time of the last question you answered, not the confirming answers.
This is because the procedure was using last answer or submission created date, but it also needs to check if there is a submission completion date, and use that if there is, as it will be the latest updated time

Fix: Include submission completion date in last updated calculation

---

tests/Dfe.PlanTech.AzureFunctions.E2ETests/EntityTests/EntityTests.cs
tests/Dfe.PlanTech.AzureFunctions.E2ETests/EntityTests/RecommendationChunkTests.cs
tests/Dfe.PlanTech.AzureFunctions.E2ETests/Generators/RecommendationChunkGenerator.cs
tests/Dfe.PlanTech.AzureFunctions.E2ETests/README.md

The caching implementation and recommendation page redesign have broken the azure E2E tests as these expect a cache handler and recommendations to have titles. Both fixed
Following the instructions in the readme and running dbup generates all the database tables in the master database, which is generally best avoided. Added a step to create a dedicated db to create the content in and run the tests against

Fix azure E2E tests post caching and redesign

---

src/Dfe.PlanTech.Domain/Questionnaire/Models/IHasContentComponent.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationChunkContentDbEntity.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationIntroContentDbEntity.cs
src/Dfe.PlanTech.Infrastructure.Data/Dfe.PlanTech.Infrastructure.Data.csproj
src/Dfe.PlanTech.Infrastructure.Data/Repositories/RecommendationsRepository.cs
tests/Dfe.PlanTech.Infrastructure.Data.UnitTests/Repositories/RecommendationsRepositoryTests.cs

- Adds validation/error handling in case of a join for a `ContentComponent` has a null value. Logs errors if any found.
- Improves tests for `RecommendationsRepository`. Some tests were not actually doing anything, so the code has been modified to ensure that the tests work as expected.

feat: Ignore invalid content relationships

---

README.md

The SonarCloud badge in the readme linked to `DFE-Digital_school-account`. Which isn't our project, and was also not found.
Amended to the correct link. Now shows correctly.

docs(readme): Fix Sonarcloud badge link

---

src/Dfe.PlanTech.Domain/Extensions/StringHelpers.cs
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/dynamic-page-validator/helpers/slugify-chunks.js
tests/Dfe.PlanTech.Web.UnitTests/Models/ComponentModelTests.cs

Ticket: [220949](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/220949)
Make RecommendationChunk slugs (which are the only slugs produced programmatically) with the slugs defined in Contentful by retaining hyphens (so "back-up broadband" becomes "back-up-broadband", not "backup-broadband").

feat: Retain hyphens in Recommendation Chunk slugs

---

src/Dfe.PlanTech.AzureFunctions/Dfe.PlanTech.AzureFunctions.csproj
src/Dfe.PlanTech.AzureFunctions/Functions/QueueReceiver.cs
src/Dfe.PlanTech.AzureFunctions/Program.cs
src/Dfe.PlanTech.AzureFunctions/README.md
src/Dfe.PlanTech.AzureFunctions/Services/CacheHandler.cs
src/Dfe.PlanTech.AzureFunctions/Startup.cs
src/Dfe.PlanTech.Domain/Persistence/Models/CacheRefreshConfiguration.cs
src/Dfe.PlanTech.Domain/Persistence/Models/ContentfulOptions.cs
src/Dfe.PlanTech.Infrastructure.Data/CmsDbContext.cs

Addresses ticket #222301.
Amends the Azure Function App to retrieve secrets from the Key Vault directly, by adding the Azure Key Vault IConfiguration provider.
- Add Key Vault IConfiguration provider to the Function App
- Amends a couple of configuration/option classes to use the [options pattern](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-8.0) where appropriate.
- Whilst this isn't needed, it simplifies the process with injecting these classes, especially when the appropriate secrets already follow the correct _naming_ convention required.
- Adds initial `README.md` to the project, which needs to be expanded in future.
1. Ensure that you can access the Key Vault locally.
1. You will need to be logged in with a user with appropriate …

feat: Add Key Vault IConfiguration provider

---

src/Dfe.PlanTech.Application/Content/Queries/GetRichTextsQuery.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetRichTextsQueryTests.cs

Draft text bodies weren't showing when use Preview was turned on as the condition was the wrong way round

Fix: Preview for rich text

---

.github/workflows/e2e-tests.yml
.github/workflows/matrix-deploy.yml

Updates workflows to run e2e tests and deployments when the C&S Submodule is updated 
The recent commit to swap the C&S submodule to point at main broke the landing page locally. We didn't see this until now because git submodules don't automatically update, and as we hadn't done an update in a while, we hadn't pulled in the breaking change.
We should be running the e2e tests whenever we update the submodule to make sure we don't have conflicts and breaking changes.
Deployments should also be triggered by a C&S submodule update so an isolated C&S change is permitted

Fix: test and deploy on cs update

---

src/Dfe.PlanTech.AzureFunctions/Functions/QueueReceiver.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Functions/QueueReceiverTests.cs

Addresses the cause of ticket #222371, but does not fix existing data.
Fixes an issue where join tables could be updated with null references, if messages were processed in same run.
This was only identified in `RecommendationChunkContent` joins, but likely existed in other join tables.
- Clear tracked entities in the CmsDbContext before processing any Contentful webhook payload
1. Turn off the `QueueReceiver` function in dev
2. Modify a recommendation chunk and publish the changes.
3. Modify one of the contents for that recommendation chunk, and publish the changes
4. Run the Azure Function locally from the development or main branc
The function should run, and:
1. Update the recommendation chunk (from step 2)
2. For step 3, it should update the content, _and clear the ContentComponentId …

fix(function): Clear entity tracking

---

src/Dfe.PlanTech.Application/Content/Queries/GetSubTopicRecommendationQuery.cs
src/Dfe.PlanTech.Web/Controllers/RecommendationsController.cs
src/Dfe.PlanTech.Web/Routing/GetRecommendationRouter.cs
src/Dfe.PlanTech.Web/Routing/IGetRecommendationRouter.cs
tests/Dfe.PlanTech.Web.UnitTests/Controllers/RecommendationsControllerTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Routing/GetRecommendationRouterTests.cs

Adds ability to preview recommendation pages.
- Adds a route `{sectionSlug}/recommendation/{recommendationSlug}/preview/{maturity?}`
- The route is only accessible if `UsePreview` is set to true.
- If false, it'll redirect the user back to the normal recommendation route (i.e. `{sectionSlug}/recommendation/{recommendationSlug}`)
- It'll retrieve and return the recommendation page with:
- _All_ recommendation chunks for that recommendation
- Either the intro matching the `maturity` slug, or the first intro it finds in the returned recommendation section
- Adds route to preview a recommendation page in its entirity
1. Set `Contentful:UsePreview` to true
2. Visit one of your existing recommendation pages
3. Append `/preview` to the URL. You should now see _all_ recommendation chunks.
4. …

feat(recommendations): Add preview ability

---

.github/workflows/deploy-azure-function.yml
terraform/container-app/20240816-dev_plan_output.txt
terraform/container-app/20240819_test_revert_plan.txt
terraform/container-app/database.networking.tf
terraform/container-app/database.tf
terraform/container-app/functions.networking.tf
terraform/container-app/functions.tf
terraform/container-app/key-vault.networking.tf
terraform/container-app/locals.tf
terraform/container-app/main-hosting.tf
terraform/container-app/terraform-configuration.md
terraform/container-app/upgrade-scripts/README.md
terraform/container-app/upgrade-scripts/shared/keyvault/state_import.sh
terraform/container-app/upgrade-scripts/sprint_33/README.md
terraform/container-app/upgrade-scripts/sprint_33/import_keyvault_secrets.sh
terraform/container-app/upgrade-scripts/sprint_33/main.sh

** To be expanded**
Changes:
- Adds private DNS zones + endpoints for the Storage Account that the Function uses
- Adds peering for the two vnets
- Removes Key Vault settings from the Function App, as these are now handled by the Function directly/progamatically
- Adds Key Vault networking
- Adds a mini script to auto-import several secrets from the Key Vault into TF state, to make the applying process easier
- Amends the deploy Azure Function workflow to change the public network access for deployment
- Separates Functions networking into own file due to size
**To do in another PR**:
- Update architecture documentation + diagrams

feat(tf): Virtual network setup 

---

terraform/container-app/database.networking.tf
terraform/container-app/functions.networking.tf
terraform/container-app/key-vault.networking.tf
terraform/container-app/locals.tf
terraform/container-app/main-hosting.tf
terraform/container-app/upgrade-scripts/README.md
terraform/container-app/upgrade-scripts/create-import-statements.js
terraform/container-app/upgrade-scripts/shared/keyvault/state_import.sh

- Adds a variable for the SQL DB, which is "needed" for staging + prod environments
- Adds missing tags 
- Couple of little helpers for future TF usage
- Adds tags to various resources where they were missing
- Adds ability to set `mssql_max_size_gb`, which is used in staging + production due to the SQL plan differences
- Creates a script that creates Terraform import statements for you (from the error output generated in an apply), to allow easy importing of various resources if appropriate
- Fixes variables in `state_import.sh` (I renamed them previously at one point and missed a few)
- Adds a grep/command in the `upgrade-scripts/README.md` that allows you to clean up the TF plan output easily

fix(tf): Differences for prod + staging environments

---

src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2024/20240827_1056_CreateGetCurrentSubmissionIdProcedure.sql
src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2024/20240827_1058_UpdateSelectOrInsertSubmissionIdProcedure.sql
src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2024/20240827_1102_UpdateDeleteCurrentSubmissionProcedure.sql

Addresses ticket #225614
If a subtopic name changes, and a user is mid-way through a journey on that subtopic, their journey will be broken. Submitting any answer will cause them to be redirected back to the self-assessment page with an error message.
This is caused by:
1. When creating, soft-deleting, or submitting a new response for a submission, we check that the `sectionName` matches
2. When retrieving the current submission responses _from the web app_ to validate the user's journey, we _do not_ check that the `sectionName` matches
There were 2 possible fixes for this:
1. Remove the `sectionName` comparison from 1
2. Or add a `sectionName` comparison to 2
I chose 1 given that IMO there's no good reason for the sectionName to be matched (as it doesn't affect the journey, or the user), …

fix: Ignore subtopic name when retrieving submission

---

src/Dfe.PlanTech.Application/Submissions/Queries/GetSubmissionStatusesQuery.cs
src/Dfe.PlanTech.Application/Submissions/Queries/SubmissionStatusProcessor.cs
src/Dfe.PlanTech.Domain/Interfaces/IGetSubmissionStatusesQuery.cs
src/Dfe.PlanTech.Domain/Submissions/Interfaces/ISubmissionStatusProcessor.cs
src/Dfe.PlanTech.Domain/Submissions/Models/SectionStatus.cs
src/Dfe.PlanTech.Domain/Submissions/Models/SectionStatusDto.cs
tests/Dfe.PlanTech.Application.UnitTests/Submissions/Queries/CheckAnswersOrNextQuestionCheckerTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Submissions/Queries/GetSubmissionStatusesQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Submissions/Queries/SectionCompleteStatusCheckerTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Submissions/Queries/SectionNotStartedStatusCheckerTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Submissions/Queries/SubmissionStatusProcessorTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Routing/GetRecommendationRouterTests.cs

Renames `SectionStatusNew` to `SectionStatus`.
`SectionStatusNew` was named as such whilst it was being used at the _same time_ as `SectionStatus`.
The original `SectionStatus` class has gone. The `New` can now be renamed to what it should be. Rejoice.
- Renames `SectionStatusNew` to `SectionStatus`.
- Run the tests
- Poke around on the app
- Everything good?

chore: Rename section status

---

src/Dfe.PlanTech.Web/Views/Shared/_Footer.cshtml

Adds an ID to the heading "support-links" in the footer.
This is being removed by changes in C&S, as the C&S layout is using our `_Footer` partial view due to the names matching.
- Adds ID to the "Support Links" heading in the footer to prevent it being made visible

fix: Add ID to support links header

---

src/Dfe.PlanTech.Web/Authorisation/PageAuthorisationRequirement.cs
src/Dfe.PlanTech.Web/Authorisation/PageModelAuthorisationPolicy.cs
src/Dfe.PlanTech.Web/Controllers/PagesController.cs
src/Dfe.PlanTech.Web/Program.cs
tests/Dfe.PlanTech.Web.UnitTests/Authorisation/PageModelAuthorisationPolicyTests.cs

Addresses ticket 224797
The current authorisation implementation is not _quite right_.
When a user visits a page that _requires authorisation_ but is not a "page" content type (i.e. a question page, check answers page, or a recommendations page), they currently receive an error message about no organisation.
They should _instead_ be redirected to the DFE Sign In login page.
This PR fixes the above.
- Amend authorisation to handle non-"page" authentication better.
1. Run the web app
2. Make sure you are not logged in. Log out if necessary.
3. Try to visit a page (via URL) that requires authorisation and is _not_ loaded from the page controller
- I.e. a question page, check answers page, or recommendations page
4. You should be redirected to the DFE Sign In page.
Delete any rows that do not …

fix: Correct authorisation checking for non-page controller routes

---

.github/workflows/code-pr-check.yml

An update to sonar cloud scanner results in it now including multiple languages by default, so its picking up all our e2e tests and other file types during coverage checks and failing to hit the required percentage. This turns it off as per the guidance here so we can continue reporting coverage for the C# code only 
https://docs.sonarsource.com/sonarqube/9.9/analyzing-source-code/scanners/sonarscanner-for-dotnet/#known-issues
- Update code PR check pipeline to disable multiple language support
See https://github.com/DFE-Digital/sts-plan-technology-for-your-school/pull/756 for this working
Once merged we should check that the coverage on development goes back to the expected amount

fix: Turn off multilanguage support to stop incorrect coverage

---

src/Dfe.PlanTech.AzureFunctions/Mappings/EntityUpdater.cs
src/Dfe.PlanTech.AzureFunctions/Models/MappedEntity.cs
tests/Dfe.PlanTech.AzureFunctions.E2ETests/Generators/RecommendationChunkGenerator.cs
tests/Dfe.PlanTech.AzureFunctions.UnitTests/Models/MappedEntityTests.cs

Follow on fix for [#220759](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_boards/board/t/Plan%20Tech/Stories/?workitem=220759)
This fixes an issue where the Azure function
1. Has an update with an incomplete bit of content
2. Updates the existing entity with the null fields from the incoming one
3. And _only then_ sets the defaults on the Incoming entity
4. The entity is deemed valid, but might fail to insert into the database due to a null field
The intent for the ticket was to set defaults and then save them, so just needed a small tweak to when the setdefaults method is called
- Swap the setting of defaults from the validation check to UpdateEntity which is always called first
- Remove some code from the Azure function E2E tests which breaks them (will raise a …

Fix: Azure function setting defaults after entity update

---

src/Dfe.PlanTech.AzureFunctions/Dfe.PlanTech.AzureFunctions.csproj

Based off reported issues online about SDK version 1.17.4 - rollback to the previously known working version 1.17.2

Rollback azure functions worker sdk

---

.github/workflows/build-azure-function.yml

Recently, a breaking change has been made in the upload-artifact runners in GitHub Actions 
https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breaking-changes-in-github-actions-runners/
This results in them not including hidden files - and consequently not including the `.azurefunction` dependencies we need in our build. This PR is to include them so it goes back to building
Best test for this is to merge into dev and just see if it works
Check we are happy with this approach, there may be a better alternative to including the hidden files, but this will verify that its the issue

fix: Include the hidden function dependencies

---

plan-technology-for-your-school.sln
src/Dfe.PlanTech.Domain/CategorySection/CategorySectionDto.cs
src/Dfe.PlanTech.Domain/Helpers/DateTimeFormatter.cs
src/Dfe.PlanTech.Domain/Helpers/SystemTime.cs
src/Dfe.PlanTech.Domain/Helpers/TimeZoneHelpers.cs
src/Dfe.PlanTech.Domain/Interfaces/ISystemTime.cs
src/Dfe.PlanTech.Web/Views/Recommendations/RecommendationsChecklist.cshtml
tests/Dfe.PlanTech.Domain.UnitTests/Dfe.PlanTech.Domain.UnitTests.csproj
tests/Dfe.PlanTech.Domain.UnitTests/Helpers/DateTimeFormatterTests.cs
tests/Dfe.PlanTech.Domain.UnitTests/Helpers/TimeZoneHelpersTests.cs
tests/Dfe.PlanTech.Web.UnitTests/ViewComponents/CategorySectionViewComponentTests.cs

Addresses ticket [#228152](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/228152)
Fixes a bug where the time on the recommendations printout is one hour behind
- Add some shared formatting methods that can be reused by other times to encourage consistency
- based off the govuk date guidance and requirements on ticket https://www.gov.uk/guidance/style-guide/a-to-z#dates
- Add a UkNow property to the system time helper that does the conversion
Check format is correct as per ticket and that time is showing correctly

Fix timezone for recommendation print page

---

src/Dfe.PlanTech.Web/Middleware/HeadRequestMiddleware.cs
src/Dfe.PlanTech.Web/Program.cs
tests/Dfe.PlanTech.Web.UnitTests/Middleware/HeadRequestMiddlewareTests.cs

Addresses ticket [#228843](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/228843)
Adds middleware to automatically handle head requests
- New middleware that treats HEAD requests as GET requests but strips out the body. This saves us adding it to every single controller method
To test you can:
- use postman 
- or open the network tab and after fetching a page, right click the request, "copy as fetch", and change the method to "HEAD"
- The CSP was making life difficult when testing with postman so I commented it out for local testing

Fix: Add middleware to handle head requests

---

docs/adr/0038-sql-caching-mechanism.md

Addresses ticket [#224828](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/224828)
Adds an ADR doc for our approach to SQL caching
Please read through the ADR and comment on anything that doesn't make sense or needs more information, and approve if you're happy with the ADR outcome
I've tested using a custom cache on a [temp branch](https://github.com/DFE-Digital/sts-plan-technology-for-your-school/tree/temp/sql-cache-spike) (the code is all experimental and needs tidying - but will be somewhat similar to this) and it worked successfully. I:
- ran the script to create a seeded test database
- ran plan tech against it and started all the subtopics
- severed the connection to the database
- refreshed the page of each subtopic and they all successfully …

docs: ADR for sql caching

---

src/Dfe.PlanTech.Web/Views/Questions/Question.cshtml

Addresses ticket [#229447](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/229447)
Changes `hidden` to `type="hidden"` to improve accessibility of hidden inputs. The latter is designed for inputs with form data not visible to the user, whilst the former is just for hiding an element, which was still showing up for accessibility tools
Elements should still be hidden

fix: set type hidden to improve accessibility of hidden inputs

---

tests/Dfe.PlanTech.Web.E2ETests/cypress/commands/login.js

DfE SignIn has changed slightly and the button between email & password is not in the form group it was before, this accounts for that and fixes the tests

Fix e2e login following DfE signin update

---

src/Dfe.PlanTech.Web/Program.cs

Fixes issue with Application Insights no longer working due to incorrect ordering of services injection.
- Add Application Insights services first
1. Run the latest dev version of the web app
2. Load a web page
3. Check the program output - look for any instance of `Application Insights Telemetry`. There should be none
4. Run the web app from this PR
5. Load a web page
6. Check the program output - ensure that there are instances of `Application Insights Telemetry` logged
Note: if it says `unconfigured` - that's because you're missing the environment variables for the connection string and the instrumentation key. Not a problem once actually deployed, but if you want to actually test it fully let me know and I'll provide the rest of details.

fix: Application insights ordering

---

src/Dfe.PlanTech.Web/Views/Recommendations/RecommendationContent.cshtml

Amends C&S links to open in same tab.
- Amends C&S links to open in same tab
Doesn't fix all accessibility problems, but fixes something that was agreed upon.

fix: Open C&S links in same tab

---

src/Dfe.PlanTech.Application/Content/Queries/GetPageFromDbQuery.cs

If there is an exception thrown when retrieving a page from the DB, we re-throw another exception. This isn't caught higher up, and results in an error page for the user.
This change handles the thrown exception, meaning that the app then requests the page from Contentful instead as it should.
- Handle exceptions thrown by retrieving page from DB, ensuring failures are retrieving from Contentful instead
1. Ensure you cannot access the SQL DB locally (e.g. remove yourself from the network IP whitelist on the SQL server)
2. Run the web app locally - open the index page (e.g. `https://localhost:8080/`)
3. You should get an error page; verify that a request to Contentful has not been executed in the logs
1. Keep the SQL server disabled as per the existing functionality
2. Run the web app …

fix: Handle page retrieval errors when retrieving a page from DB

---

src/Dfe.PlanTech.Application/Content/Queries/GetButtonWithEntryReferencesQuery.cs
src/Dfe.PlanTech.Application/Content/Queries/GetCategorySectionsQuery.cs
src/Dfe.PlanTech.Application/Content/Queries/GetPageFromDbQuery.cs
src/Dfe.PlanTech.Application/Content/Queries/GetPageQuery.cs
src/Dfe.PlanTech.Application/Content/Queries/GetRichTextsQuery.cs
src/Dfe.PlanTech.Domain/Content/Models/PageDbEntity.cs
src/Dfe.PlanTech.Web/TagHelpers/RichText/RichTextTagHelper.cs
src/Dfe.PlanTech.Web/Views/Shared/Components/ButtonWithEntryReference.cshtml
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetButtonWithEntryReferencesQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetPageQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetRichTextsQueryTests.cs

Fixes various issues with loading of a page's content, where the original implementation no longer worked with the new caching method
- Explicitly assign loaded content for pages to the page - don't _just_ let EF Core do its thing
- Change how `GetButtonWithEntryReferencesQuery` queries the buttons from the DB; the original shouldn't have worked
- Change how `ButtonWithEntryReference.cshtml` renders links to pages as the original one didn't work
- Put a breakpoint after var page = await GetPageFromDb(slug, cancellationToken); in GetPageFromDbQuery.cs
- Debug PT locally
- Load the start page (/) and after getting the page from the db is done, cancel the page load
- Wait a few seconds
- Start another start page load, and let the debugger continue
- This loads the page in another query, …

fix: Page children retrieval

---

src/Dfe.PlanTech.DatabaseUpgrader/DatabaseExecutor.cs

Our last few runs have failed due to execution timeout of the database upgrade scripts, by default this is likely 30 seconds but the recent datafix is just over that. Increased to 10 minutes to cover anything similar
- DbUp timeout set to 10 minutes

Fix: Increase dbup timeout

---

contentful/content-migrations/helpers.js
contentful/content-migrations/migrations/20241010-2222-amend-references-view.js
contentful/content-migrations/migrations/20241014-1117-fix-releases-widget.js

Creates a new migration to fix previous migration problem.
1. Correct ordering of widget ids (i.e. first id == widget to add, second id == widget to insert before)
2. Correct widget namespace
- New migration to fix problem with release widget added in last migration
- Make `helpers.js` file for storing all content types, and a simple method to run a callback for _all_ content types

fix: Sidebar release widget 

---

src/Dfe.PlanTech.Web/Views/Shared/BackButton.cshtml
src/Dfe.PlanTech.Web/Views/Shared/_BodyEnd.cshtml
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/components/back-button-link.cy.js

Amends the back button link to show "Home", and redirect to the self-assessment page, for non-JS users.
- Duplicates back button links; one for non-JS, one for JS. 
- JS one is hidden by default
- If JS is enabled, the non-JS one gets deleted, and the JS one gets made visible.
1. Run web app with JS enabled
2. Go to a page that would display the back button
3. Verify that it looks and functions the same as before
4. Disable JS
5. Reload page
6. Verify that the back button now says "Home", and always directs to /self-assessment
I did originally just try:
- One single back button link
- Change default HREF to '/self-assessment' and the display text to 'Home'
- When page loads, use JS to amend the HREF (which we already do), and the text to 'Back'
However, when I did this, you could visibly …

fix: Amend default back button behaviour + text for non-JS users

---

.github/workflows/build-image.yml
.github/workflows/code-pr-check.yml
.github/workflows/deploy-image.yml
.github/workflows/e2e-tests.yml
.github/workflows/matrix-deploy.yml
src/Dfe.PlanTech.Web/Dockerfile

Remove references to git submodule now that C&S code has been merged with Plan Tech
Removes references to C&S git submodule in GitHub workflows and Dockerfile

Fix: remove references to c&s git submodule

---

.github/workflows/deploy-image.yml

Adds the credentials for the no organisation user to the E2E test call.
- Adds the credentials for the no organisation user to the E2E test call.

fix(cicd): Add credentials for user with noorg to E2E test call

---

src/Dfe.PlanTech.Web/Views/Recommendations/RecommendationContent.cshtml
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/recommendation-page.cy.js

Addresses ticket 234475
Adds pagination to the bottom of recommendation page
- Add pagination to bottom of recommendation content
I really dislike the approach with keeping all the different recommendation pieces on one page, and using CSS to hide/show them. It makes things like this... not ideal. However, it was chosen for some reason that I've forgotten, and it's workable, so on it goes.

feat(recommendations): Add pagination

---

src/Dfe.PlanTech.Domain/Extensions/StringHelpers.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationChunk.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationIntro.cs
tests/Dfe.PlanTech.Web.UnitTests/Models/ComponentModelTests.cs

Fixes issue with slug generator.
- Trims the regex'd string _first_
- Then replace whitespace characters with hyphens
- Then remove characters that are not alphanumeric or hyphens
- Add a backing field for the slugified header, to prevent it being ran 3x per content/intro.
Weird one this.
Basically the header name had a load of space at the end of it, so we ended up with `name-here     -`.  Also they weren't _actual_ spaces they're actually the line separator code I believe? I digress. Bt:
1. When using the exact same property in an `anchor` element directly, (`RecommendationContent.cshtml`), the slug would end up being something like `continue-with-the-thing      -`
2. When using it with the ASP Net core package we use for the DFE/GDS components, it ended up being …

fix: trim slug before replacing with hyphens

---

src/Dfe.PlanTech.Web/Views/Recommendations/RecommendationsChecklist.cshtml

Addresses ticket [#234374](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/234374)
Fixes the print button showing when JS is disabled
Ensure the print this page button is hidden on the recommendation printout when JS is disabled and unaffected otherwise

Fix: Remove print button from recommendation printout when no JS

---

src/Dfe.PlanTech.Infrastructure.Data/CmsDbContext.cs

The CMSDbContext wasn't aware of the triggers on these tables so threw errors during certain inserts as it was using an approach that doesn't support them. This just tells the modelbuilder about them all, just as we do in `PlanTechDbContext` to resolve it.
Run locally and make sure content inserts that were failing before are working correctly locally

Fix: Trigger errors

---

tests/Dfe.ContentSupport.Web.Tests/Dfe.ContentSupport.Web.Tests.csproj
tests/Dfe.PlanTech.Application.UnitTests/Dfe.PlanTech.Application.UnitTests.csproj
tests/Dfe.PlanTech.CmsDbMigrations.E2ETests/Dfe.PlanTech.CmsDbMigrations.E2ETests.csproj
tests/Dfe.PlanTech.Domain.UnitTests/Dfe.PlanTech.Domain.UnitTests.csproj
tests/Dfe.PlanTech.Domain.UnitTests/Helpers/DateTimeFormatterTests.cs
tests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests.csproj
tests/Dfe.PlanTech.Infrastructure.Data.UnitTests/Dfe.PlanTech.Infrastructure.Data.UnitTests.csproj
tests/Dfe.PlanTech.Infrastructure.ServiceBus.UnitTests/Dfe.PlanTech.Infrastructure.ServiceBus.UnitTests.csproj
tests/Dfe.PlanTech.Infrastructure.SignIn.UnitTests/Dfe.PlanTech.Infrastructure.SignIn.UnitTests.csproj
tests/Dfe.PlanTech.Web.UnitTests/Dfe.PlanTech.Web.UnitTests.csproj

Recent package upgrade broke the test runners/detection. This fixes that.
- Add `xunit.runner.visualstudio` project to unit test projects
We should amend our unit test pipelines to have some bare basic logic that goes something like "if unit tests have ran -> at least one unit test must have ran and succeeded"

fix: Add xunit runners to unit test projects

---

src/Dfe.ContentSupport.Web/Views/Shared/_Print.cshtml
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/contentsupport/pages/feedback.cy.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/contentsupport/pages/print-button.cy.js

Fix rendering of print button on C&S pages
- View a C&S page with print button enabled
- Verify print button renders correctly
- Verify print button is not displayed with js disabled or when printing page

fix: C&S print button

---

src/Dfe.PlanTech.Application/Persistence/Interfaces/IPlanTechDbContext.cs
src/Dfe.PlanTech.Application/Submissions/Queries/GetSubmissionStatusesQuery.cs
src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2024/20241104_1200_RemoveContentfulDependencies.sql
src/Dfe.PlanTech.Domain/Submissions/Interfaces/IGetSubmissionStatusesQuery.cs
src/Dfe.PlanTech.Infrastructure.Data/PlanTechDbContext.cs
src/Dfe.PlanTech.Web/ViewComponents/CategorySectionViewComponent.cs
tests/Dfe.PlanTech.Application.UnitTests/Submissions/Queries/GetSubmissionStatusesQueryTests.cs
tests/Dfe.PlanTech.Web.UnitTests/ViewComponents/CategorySectionViewComponentTests.cs

Addresses ticket [#235157](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/235157)
Removes any dependencies on the Contentful schema
Ignore the E2E failures - this will be another one that I'll have to run the script on manually before merge, its incompatible with the current DB
- Amends the `GetSectionStatuses` procedure to use a list of sectionIds instead of the categoryId
- This way it doesn't need to access any contentful tables to look up the relevant submissions
If you're using a tool like rider, datagrip or any other database IDE which supports scripting to file/clipboard you can script the dbo schema to file and verify that there are no longer any dependencies on the `Contentful` schema. Or we don't have that many stored procedures so you can skim …

chore: Remove all Contentful schema dependencies

---

src/Dfe.PlanTech.Domain/Questionnaire/Interfaces/IHeaderWithContent.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationChunk.cs
src/Dfe.PlanTech.Domain/Questionnaire/Models/RecommendationIntro.cs
src/Dfe.PlanTech.Web/Views/Recommendations/RecommendationContent.cshtml
src/Dfe.PlanTech.Web/Views/Recommendations/RecommendationPrintContent.cshtml
src/Dfe.PlanTech.Web/Views/Shared/Components/HeaderWithContent.cshtml
src/Dfe.PlanTech.Web/Views/Shared/Components/VerticalNavigation/Default.cshtml
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/dynamic-page-validator/validators/completion-tags.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/dynamic-page-validator/validators/recommendation-chunks.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/dynamic-page-validator/validators/recommendation-intro.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/dynamic-page-validator/validators/validate-recommendations.js
tests/Dfe.PlanTech.Web.UnitTests/Models/ComponentModelTests.cs

Addresses ticket [#234960](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/234960)
Changes to display of Recommendations sidebar.
The design for the ticket is based on [this prototype](https://content-and-support-3394b320ea96.herokuapp.com/sandbox/pt-recomendation-c1/prototype-a/recomendations#)
- Recommendation Intro header is displayed in the sidebar, pagination and slug as 'Overview' (main header and print view unchanged)
- Sidebar header changed to 'Recommendations' from 'List of actions'
- Added and amended unit tests and amended E2E tests.
Test against a recommendations page as per normal.
To run E2E tests while running locally, change the url in `cypress.env.json` to localhost, and open cypress using localhost as the baseUrl (see cypress E2E readme …

feat: recommendation sidebar accessibility changes

---

src/Dfe.PlanTech.Web/Views/Recommendations/RecommendationContent.cshtml

Addresses ticket [#235842](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_boards/board/t/STS%202.0%20Scrum%20Teams/Stories/?workitem=235842)
Move link to printable recommendation page so that it is above the pagination links
- Navigate to a recommendation
- Verify that the link to printable page is above the pagination links and that it matches the image on the ticket

feat: move print link above pagination links

---

terraform/container-app/main-hosting.tf
terraform/container-app/terraform-configuration.md

Addresses ticket 234276
Adds `AZURE_CLIENT_ID` back to the container app environment variables, this time with the correct value.
**Note: this is dependant on [this PR](https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting/pull/438) in the DFE TF module. Which has not gone in yet.**
- Set `AZURE_CLIENT_ID` environment variable on the container app
- Increment module version

fix(tf): Correct Azure Client ID

---

src/Dfe.PlanTech.Infrastructure.Redis/JsonSerialiser.cs

Fixes issue with serialisation where the parent has a lot of objects with references
- Set [reference handler to preserve](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/preserve-references)

fix(redis): Preserve references in serialisation

---

src/Dfe.PlanTech.Domain/Content/Interfaces/INotificationBanner.cs
src/Dfe.PlanTech.Domain/Content/Models/NotificationBanner.cs
src/Dfe.PlanTech.Web/Views/Shared/Components/NotificationBanner.cshtml
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/dynamic-page-validator/dynamic-page-validator-readme.md
tests/Dfe.PlanTech.Web.E2ETests/cypress/helpers/content-validators/content-validator.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/helpers/content-validators/notification-banner-validator.js
tests/Dfe.PlanTech.Web.UnitTests/Models/ComponentBuilder.cs
tests/Dfe.PlanTech.Web.UnitTests/ViewComponents/NotificationBannerTests.cs

Addresses ticket [#236011](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/236011)
Adds support for displaying a Notification banner as a piece of Content for a page
- Adds another content model similar to warning component for a notification banner
- This content type has been created in Contentful under the api name `notificationBanner`
- Try making one yourself in Contentful added to any page and see that it renders as expected, and that you can toggle it on and off, add links, etc, as the ticket requests.
1. Create the `NotificationBanner` content type in staging/prod contentful
2. Alter the `Page` content type to accept notification banners within the list of content

feat: Add support for notification banners

---

src/Dfe.PlanTech.Infrastructure.Redis/RedisCache.cs

Relates to [#234426](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/234426)
Fixes a bug where some models like `RichText` which are `ContentComponent` types, don't actually have `SystemDetails` as sub-content of something else and therefore caused the dependency loop to fail
Also ensures the typeofs work with inheritance
- Test making changes to various different bits of content on a page and ensure the page is correctly invalidated and refreshes with the new up to date content
I chose not to change `RichText` to not inherit because it seems risky - but might be something we look into

fix: Fix bug where dep collection fails if sys details are missing

---

src/Dfe.PlanTech.Web/Controllers/ContentController.cs
src/Dfe.PlanTech.Web/Controllers/PagesController.cs
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/contentsupport/pages/not-found.cy.js
tests/Dfe.PlanTech.Web.UnitTests/Controllers/ContentControllerTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Dfe.PlanTech.Web.UnitTests.csproj

Addresses ticket 2335547
If a C&S page is not found, redirect user to 404 page.
- Use 404 page for missing C&S pages
Try slugs like `/content` or `/content/this-definitely-does-not-exist`, and make sure you get the 404 page.

fix: Use 404 page for missing C&S pages

---

src/Dfe.PlanTech.Web/appsettings.json

Removes the contact email address from concurrent user error message ahead of Zendesk integration

chore: remove email address from error message

---

tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/contentsupport/pages/cs-page.cy.js
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/contentsupport/pages/print-button.cy.js

Update C&S E2E tests so that they are run against `hello-world` page

fix: e2e tests for c&s should test hello-world

---

src/Dfe.PlanTech.Web/Views/Pages/Page.cshtml
src/Dfe.PlanTech.Web/Views/Shared/Components/NotificationBanner.cshtml
src/Dfe.PlanTech.Web/Views/Shared/Components/Page.cshtml
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/accessibility-page.cy.js

Small changes to where the Organisation title renders so that we can put the banner before the title
Also makes the banner 2/3rd width
- Moves org title into page rendering
- Makes banner 2/3 width
- Only renders the banner if the error banner is not showing
- Fixes accessibility page e2e tests to search for back button (it will fail in staging if we just fix the dev content)
Check it looks like new mockup from Sam using BeforeContent in contentful as place where banner goes

fix: Move org title to support banner and make 2/3 width

---

src/Dfe.PlanTech.Domain/Database/DatabaseOptions.cs
src/Dfe.PlanTech.Web/ProgramExtensions.cs
src/Dfe.PlanTech.Web/appsettings.json
tests/Dfe.PlanTech.Domain.UnitTests/Database/DatabaseOptionsTests.cs

No ticket for this I just had time to fix it and didn't want to start another ticket at the end of the sprint with how little time I have to implement it today.
Adds retry on failure to DB requests
1. Enables retry on failure using EF Core's built in functionality.
2. Adds a `DatabaseOptions` record for configuring the options used above
3. Adds default settings to appsettings.json.

feat(db): Add retry on failure to DB requests

---

.gitignore
contentful/content-migrations/migrations/20241118-1239-add-content-reference-to-nav-link.js
src/Dfe.PlanTech.Domain/Content/Interfaces/IHasSlug.cs
src/Dfe.PlanTech.Domain/Content/Interfaces/INavigationLink.cs
src/Dfe.PlanTech.Domain/Content/Interfaces/IPage.cs
src/Dfe.PlanTech.Domain/Content/Models/NavigationLink.cs
src/Dfe.PlanTech.Infrastructure.Contentful/Persistence/EntityResolver.cs
src/Dfe.PlanTech.Web/Content/ContentService.cs
src/Dfe.PlanTech.Web/Models/Content/ContentBase.cs
src/Dfe.PlanTech.Web/Models/Content/ContentSupportPage.cs
src/Dfe.PlanTech.Web/Models/Content/IContentSupportPage.cs
src/Dfe.PlanTech.Web/Models/Content/Mapped/CsPage.cs
src/Dfe.PlanTech.Web/TagHelpers/FooterLinkTagHelper.cs
src/Dfe.PlanTech.Web/ViewComponents/FooterLinksViewComponent.cs
src/Dfe.PlanTech.Web/Views/Shared/Components/FooterLinks/Default.cshtml
tests/Dfe.PlanTech.Web.UnitTests/TagHelpers/FooterLinkTagHelperTests.cs

Completes 235545.
Adds the ability for navigation links (footer links) to not only have "href" fields on Contentful, but also directly link to content. This should reduce the amount of changes needed if linking to an internal page.
- Adds link to content field in navigation links
- Amends a few C&S models to implement `IContentComponent` 
- Run app
- Test the footer links.
- Test the existing links; no problems?
- I've added two links to dev/test for testing.
- `Link to accessibility page test`; links to accessibility page using the content field. Does this link to the accessibility page?
- `Should be accessibility, might be cookies` links to accessibility page via content field, but also has href for cookies. Content link should take priority over href, so make sure this links to …

feat(235545): Add link to content from navigation links

---

src/Dfe.PlanTech.Domain/Content/Models/ContentComponentJsonExtensions.cs
src/Dfe.PlanTech.Domain/Helpers/ReflectionHelpers.cs
src/Dfe.PlanTech.Infrastructure.Redis/JsonSerialiser.cs
src/Dfe.PlanTech.Infrastructure.Redis/RedisCache.cs
tests/Dfe.PlanTech.Infrastructure.Redis.UnitTests/ContentComponentJsonExtensionsTests.cs

Fixes issue in #237764 where the navigation links were not being deserialised properly, as the content is of type `IContentComponent` by the polymorphic serialisation was of type `ContentComponent`.
Also fixes handling of Redis connection errors. Whilst errors in `Get` or `Create` were handled, there was no handling of the initial database connection in `GetOrCreate`. If there was an error connecting to the Redis server straight away then it would just fail. It should now return the result of what the `action` argument is.
- Fix navigation links deserialisation by handling `IContentComponent` polymorphic serialisation
- Handle database connection errors in Redis `GetOrCreate`
1. Change your redis connection string to a non-existent server; ensure that the pages (etc.) load from Contentful …

fix: Handle IContentComponent serialisation + Redis errors better

---

src/Dfe.PlanTech.Application/Responses/Queries/GetLatestResponsesQuery.cs
src/Dfe.PlanTech.DatabaseUpgrader/Scripts/2024/20241127_1700_AddSubmissionViewedColumn.sql
src/Dfe.PlanTech.Domain/CategorySection/CategorySectionRecommendationDto.cs
src/Dfe.PlanTech.Domain/Submissions/Interfaces/IGetLatestResponsesQuery.cs
src/Dfe.PlanTech.Domain/Submissions/Models/SectionStatusDto.cs
src/Dfe.PlanTech.Domain/Submissions/Models/Submission.cs
src/Dfe.PlanTech.Web/Routing/GetRecommendationRouter.cs
src/Dfe.PlanTech.Web/ViewComponents/CategorySectionViewComponent.cs
src/Dfe.PlanTech.Web/Views/Shared/Components/CategorySection/SubtopicRecommendation.cshtml
tests/Dfe.PlanTech.Application.UnitTests/Submissions/Queries/GetLatestResponsesQueryTests.cs
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/check-answer-page.cy.js

Addresses ticket [#237183](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/237183)
Now shows the "New" tag until a recommendation has actually been viewed by someone in the organisation
- Adds a `viewed` column to the `submission` table that defaults to false
- Returns it from the `GetSectionStatuses` procedure so that the page can show the `"New"` tag next to a recommendation whenever `viewed` is false
- On page load of recommendations, sets `viewed` to true
I've already applied the SQL changes to dev, so it should work as soon as you swap to this branch - you can also use the test database to verify the script works.
Check that:
- Completing a topic results in a new tag
- On refreshing the page it persists
- It stays if you restart but not complete the …

feat: store if a recommendation is viewed for new tag

---

src/Dfe.PlanTech.Domain/Persistence/Models/ApiAuthenticationConfiguration.cs
src/Dfe.PlanTech.Web/Authorisation/ApiKeyAuthorisationFilter.cs
tests/Dfe.PlanTech.Web.UnitTests/Authorisation/ApiKeyAuthorisationFilterTests.cs

Updates `ApiKeyAuthorisationFilter` to handle missing configuration and invalid API keys more robustly
- Ensure API authorisation failures exit after one failure found
Currently there are 3 steps in validating the API key supplied to the app:
1. Check the header value exists in the expected format.
2. Check that we have the valid API key in our config. 
3. Check that the supplied API key matches the valid API key
If any of those steps are false, then we return an unauthorised result.
_However_, we don't actually stop the rest of the validations if any of them are incorrect. E.g. if the user doesn't supply an API key (step 1 fails), we set it to return an authorised result but still continue processing steps 2 + 3. This can lead to system errors later on where we end up with null reference …

fix: Update ApiKeyAuthorisationFilter to handle auth failures more robustly

---

src/Dfe.PlanTech.Web/Middleware/RobotsTxtMiddleware.cs
src/Dfe.PlanTech.Web/Models/RobotsConfiguration.cs
src/Dfe.PlanTech.Web/Program.cs
src/Dfe.PlanTech.Web/appsettings.json
tests/Dfe.PlanTech.Web.UnitTests/Middleware/RobotsTxtMiddlewareTests.cs

Adds robots.txt as per ticket 238738
- Adds middleware for generating a robots.txt file at path {host}/robots.txt
- Run the app
- Navigate to {host}/robots.txt
- Ensure that the file is loaded, and the generated data matches the config in `appsettings.json`
Originally was just going to create a static `robots.txt` file, but this will allow configuration per environment, or modifying easily in the future without having to redeploy/upload anything.

feat: Add middleware for handling + generating robots.txt

---

.github/workflows/matrix-deploy.yml
.github/workflows/qa-viz.yml

Changes the inputs of the qa workflow from a use preview option to an environment option, previously it wasn't using the staging vars so is outputting dev content, this should fix that.

fix: Add environment to inputs on qa visualiser workflow

---

.github/workflows/deploy-image.yml
src/Dfe.PlanTech.Application/Caching/Interfaces/ICmsCache.cs
src/Dfe.PlanTech.Application/Content/Queries/GetEntityFromContentfulQuery.cs
src/Dfe.PlanTech.Application/Content/Queries/GetNavigationQuery.cs
src/Dfe.PlanTech.Application/Content/Queries/GetPageQuery.cs
src/Dfe.PlanTech.Application/Content/Queries/GetSubTopicRecommendationQuery.cs
src/Dfe.PlanTech.Application/Persistence/Commands/WebhookMessageProcessor.cs
src/Dfe.PlanTech.Application/Persistence/Interfaces/IContentRepository.cs
src/Dfe.PlanTech.Application/Persistence/Models/GetEntitiesOptions.cs
src/Dfe.PlanTech.Application/Questionnaire/Queries/GetSectionQuery.cs
src/Dfe.PlanTech.Domain/Extensions/StringHelpers.cs
src/Dfe.PlanTech.Domain/Persistence/Interfaces/IGetEntitiesOptions.cs
src/Dfe.PlanTech.Infrastructure.Contentful/Helpers/ContentfulSetup.cs
src/Dfe.PlanTech.Infrastructure.Contentful/Persistence/CachedContentfulRepository.cs
src/Dfe.PlanTech.Infrastructure.Contentful/Persistence/ContentfulRepository.cs
src/Dfe.PlanTech.Infrastructure.Redis/IRedisDependencyManager.cs
src/Dfe.PlanTech.Infrastructure.Redis/RedisCache.cs
src/Dfe.PlanTech.Infrastructure.Redis/RedisDependencyManager.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetEntityFromContentfulQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetNavigationQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetPageQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Content/Queries/GetSubTopicRecommendationQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Persistence/Commands/WebhookMessageProcessorTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Persistence/GetEntitiesOptionsTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Questionnaire/Queries/GetSectionQueryTests.cs
tests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests/Persistence/CachedContentfulRepositoryTests.cs
tests/Dfe.PlanTech.Infrastructure.Contentful.UnitTests/Persistence/ContentfulRepositoryTests.cs
tests/Dfe.PlanTech.Infrastructure.Redis.UnitTests/RedisCacheTestHelpers.cs
tests/Dfe.PlanTech.Infrastructure.Redis.UnitTests/RedisCacheTests.cs
tests/Dfe.PlanTech.Infrastructure.Redis.UnitTests/RedisDependencyManagerTests.cs

Addresses ticket [#237738](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/237738)
This changes redis caching from being done by the application layer, to being done on the repository instead. This way it lives in just two places and covers all contentful calls.
It also fixes two bugs in dependency management
- All cache methods moved into the Contentful repository class and removed from elsewhere
- Updates deployment pipeline to clear the cache upon release (see historic flush redis cache workflow in actions history as tests that this works)
- For whole content collections, the key is always `<contentType>s`
- For content queried with options, the key is `<contentType>_<serialisedOptions>`
- Amends existing dependency management to check whether there …

Fix: improve redis caching edge cases

---

src/Dfe.PlanTech.Domain/ServiceBus/Models/ServiceBusOptions.cs
src/Dfe.PlanTech.Infrastructure.ServiceBus/ContentfulServiceBusProcessor.cs
src/Dfe.PlanTech.Infrastructure.ServiceBus/DependencyInjection.cs
src/Dfe.PlanTech.Web/appsettings.Development.json
tests/Dfe.PlanTech.Infrastructure.ServiceBus.UnitTests/ContentfulServiceBusProcessorTests.cs

Adds option to disable the Service Bus processing on the web app; this should allow us to test various things easier (e.g. caching) by disabling the job on dev.
- Adds configuration to disable Service Bus reading + processing for Contentful content changes
Run the app from this branch and ensure that the Service Bus processing still happens like normal (check console).
Then set ServiceBusOptions:EnableQueueReading to false in `appsettings.Development.json` and restart app. Validate that it no longer reads + processes the queue.

feat: Add option to disable Service Bus processing

---

src/Dfe.PlanTech.Infrastructure.Redis/JsonSerialiser.cs
src/Dfe.PlanTech.Web/appsettings.Staging.json

Addresses ticket [#245053](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/245053)
Fix from Jim discussed in the call yesterday
- Increase JSON max depth
- Also set `UsePreviewApi` to true, as this broke last time we released to staging
- Change your .NET secrets to use staging and production contentful instead of dev
- Use local redis
- Clear your redis cache
- Run PT locally on dev branch
- See self-assessment page is dead
- Checkout this branch
- Clear redis cache locally
- See self-assessment page is revived

Fix: Increase json max depth

---

src/Dfe.PlanTech.Domain/CategorySection/CategorySectionRecommendationDto.cs
src/Dfe.PlanTech.Domain/Submissions/Models/SectionStatusDto.cs
src/Dfe.PlanTech.Web/Views/Shared/Components/CategorySection/SubtopicRecommendation.cshtml

Addresses ticket [#245585](www.ticket-link.com)
Allowed DTO and related classes to accept NULL values from GetSectionStatuses stored procedure. Changed display logic on Razor page.
Follow instructions to reproduce on [ticket](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/245585/) in development branch. Then swap to this branch and check functionality is fixed.
- [v] Title uses [Angular commit convention](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
- [v] PR targets development branch

fix (245585): Allow nulls returned from GetSectionStatuses

---

contentful/export-processor/.gitignore
contentful/export-processor/content-types/recommendation-section.js
contentful/export-processor/content-types/section.js
contentful/export-processor/data-mapper.js
contentful/export-processor/data-tools.js
contentful/export-processor/errors/error-logger.js
contentful/export-processor/generate-test-suites.js
contentful/export-processor/helpers/json.js
contentful/export-processor/helpers/log.js
contentful/export-processor/test-suite/test-suite.js
contentful/export-processor/test-suite/write-csvs.js
contentful/export-processor/user-journey/minimum-path-calculator.js
contentful/export-processor/user-journey/path-calculator.js
contentful/export-processor/user-journey/path-part.js
contentful/export-processor/user-journey/user-journey.js
contentful/export-processor/write-user-journey-paths.js

Fixes a couple of problems with the test suite generation in the export-processor, as well as adding minor things such as more logging outputs, JSDoc comments, etc.
- [recommendation-section.js](/contentful/export-processor/content-types/recommendation-section.js): modify `getChunksForPath` to only compare chunk IDs for unique chunks
- [section.js](/contentful/export-processor/content-types/section.js): ensure _all paths_ generated for `toMinimalOutput` are "minimalised" - i.e. only return the question text and answer text, not _the actual question and answer objects_
- log.js - logging helper
- json.js - Extract a method what was used for handling JSON.stringify errors caused by too large an object being stringified. This should actually not be needed anymore due to the fix in section.js …

fix(contentful): Export processor fixes

---

.editorconfig

Addresses ticket [#236403](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/236403)
Add line endings to .editorconfig to prevent test failures based on MS/Mac/Unix differences.
- end-of-line = lf added to editorconfig
- Automated settings update by Visual Studio
Pull down the branch, check nothing breaks and no line ending issues with unit tests
None

chore(236403): add line endings to .editorconfig

---

contentful/export-processor/test-suite/test-suite.js
src/Dfe.PlanTech.Web/Views/Shared/Components/VerticalNavigation/Default.cshtml
tests/Dfe.PlanTech.Web.E2ETests/cypress/e2e/pages/recommendation-page.cy.js

Addresses ticket [#246010](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_boards/board/t/Team%20Build/Stories/?workitem=246010)
Fixes the word assessment on the default.cshtml page where it was mis-spelt as assesment. Also changed where tests were using that.
- Docs change one
- Run the solution 
- Complete a journey
- Ensure the link at the top says "Go to self-assessment topics"
What steps are required for release, if any? E.g. Key Vault secrets, Terraform changes, etc.
Standard release

fix(246010) - Typo fix on the word assessment.

---

src/Dfe.PlanTech.Application/Extensions/StringExtensions.cs
src/Dfe.PlanTech.Web/Models/PageViewModel.cs
src/Dfe.PlanTech.Web/Views/Shared/Components/Title.cshtml
tests/Dfe.PlanTech.Web.UnitTests/Helpers/StringExtensionsTests.cs

Replace hyphens with non breaking hyphens so that they behave the same as full words
Also added unit tests that should cover this and point of failure
Minor
- Replace hyphen functionality in string extensions
Non-functional changes (e.g. documentation)
- unit tests to cover this

Replace standard Hyphens with non breaking hyphens

---

tests/Dfe.PlanTech.Web.UnitTests/Content/ContentServiceTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Content/ModelMapperTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Controllers/ContentControllerTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Dfe.PlanTech.Web.UnitTests.csproj

Addresses ticket [#237003](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/237003)
Switch from Moq to NSubstitute for C&S Unit tests, removed package references.
Run tests and app, check nothing failing!

test(237003): replace Moq with NSubstitute in C&S unit tests

---

.github/workflows/contentful-backup.yml

This is to change the contentful-backup to default to the StagingUnprotected github environment so it runs without any protection rules.

Update auto contentful-backup to use StagingUnprotected -> Main

---

utils/update-gias-data/src/update_database.py

This will add the test rows to the GIAS Updater when it runs. At the moment it removes any data in the establishmentGroup/Links if it does not exist from the downloaded data. I've added the data to the temporary table prior to updating.

Added test rows to the GIAS Updater

---

src/Dfe.PlanTech.Web/Views/Recommendations/Header.cshtml
src/Dfe.PlanTech.Web/Views/Shared/_Layout.cshtml

Only display back button non-mat pages.
Moved beta partial outside of the div in recommendations/header.cshtml.

v2.19.0 - Only display back-button on non-mat pages. 

---

src/Dfe.PlanTech.Web/Views/Shared/Components/GroupsDashboard/GroupsSubtopics.cshtml

Addresses ticket [#258218](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/258218)
Section names on Groups Dashboard are wrapping inappropriately when the 
- Applied css override to non-link section names
Log in as MAT user, select Miscellaneous from the school selection (this should have no submissions for Digital technology registers), check that 'Digital technology registers' in the dashboard table does not wrap.
None

fix (258218): stop groups dashboard section name from wrapping when not a link

---

src/Dfe.PlanTech.Web/Views/Groups/Print.cshtml

Addresses ticket [#258447](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/258447)
Fix for 'View and print all recommendations' link in the groups recommendations view for the F&M Roles section (only this section had the bug because it is the one with a difference between the slugified section name and the section slug).
- Change to the slug being passed to the controller action
Log in as MAT user, select Community School (this should have the F&M Roles section already completed), click Roles to view the recommendations and click the 'View and print all recommendations' link. Should show the print page and not error. Check another section to confirm that others are unaffected.
None

fix(258447): F&M roles print link

---

src/Dfe.PlanTech.Domain/CategorySection/CategorySectionDto.cs
src/Dfe.PlanTech.Web/Views/Shared/Components/CategorySection/SubtopicRecommendation.cshtml
src/Dfe.PlanTech.Web/Views/Shared/Components/CategorySection/Subtopics.cshtml
tests/Dfe.PlanTech.Web.UnitTests/ViewComponents/CategorySectionViewComponentTests.cs

Added card design to self-assessment page with dynamic routing to relevant pages depending on SA status
[256578](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/256578)
Added card design implementation to landing page
The design for the ticket is based on:
https://plantech.herokuapp.com/sprint14/landing
- CategorySectionDto status checking
- Suptopics.cshtml required card classes
- SubtopicRecomendations.cshtml partial changes
Smoke test and check routing goes to where expected (routing will change with upcoming home journey tickets)
N/A
257799 home journey branch will hold new feature changes
- [ x] Title uses [Angular commit convention](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
- [ x] Unit tests …

256578 Added self assessment card view implementation

---

src/Dfe.PlanTech.Application/Constants/UrlConstants.cs
src/Dfe.PlanTech.Web/Controllers/GroupsController.cs
src/Dfe.PlanTech.Web/Models/GroupsSelectorViewModel.cs
src/Dfe.PlanTech.Web/Views/Groups/GroupsSelectSchool.cshtml
tests/Dfe.PlanTech.Web.UnitTests/Controllers/GroupsControllerTests.cs

Addresses ticket [#258952](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/258952)
Adds text to bottom of school selection directing users to the Contact Us page
The design for the ticket is based on [the prototype](https://plantech.herokuapp.com/sprint12/prototype/change-school).
- Adds ContactLink query to Groups Controller
- Adds link to ViewModel and View
Log in as MAT user to view Select a school, check link displays and works.

feat(258952): adds contact us link and text to MAT select a school view

---

.github/actions/azure-check-expiry/action.yml
.github/workflows/deploy-image.yml

Old 2023 AZ CLI versions being used in the deploy-image and check-expiry pipelines.,

(task): Updated AZ CLI version in check-expiry and deploy-image

---

src/Dfe.PlanTech.Web/Dfe.PlanTech.Web.csproj

Removes buildWebAssets=true command to prevent css changes appearing on each build

fix: revert change that builds web assets on local build

---

src/Dfe.PlanTech.Application/Responses/Commands/ProcessSubmissionResponsesDto.cs
src/Dfe.PlanTech.Application/Submissions/Queries/SubmissionStatusProcessor.cs
src/Dfe.PlanTech.Domain/Submissions/Interfaces/IProcessSubmissionResponsesCommand.cs
src/Dfe.PlanTech.Domain/Submissions/Interfaces/ISubmissionStatusProcessor.cs
src/Dfe.PlanTech.Web/Controllers/CheckAnswersController.cs
src/Dfe.PlanTech.Web/Controllers/QuestionsController.cs
src/Dfe.PlanTech.Web/Models/RecommendationsViewModel.cs
src/Dfe.PlanTech.Web/Routing/ChangeAnswersRouter.cs
src/Dfe.PlanTech.Web/Routing/CheckAnswersRouter.cs
src/Dfe.PlanTech.Web/Routing/GetQuestionBySlugRouter.cs
src/Dfe.PlanTech.Web/Routing/GetRecommendationRouter.cs
src/Dfe.PlanTech.Web/Routing/ICheckAnswersRouter.cs
src/Dfe.PlanTech.Web/Views/Recommendations/YSA.cshtml
tests/Dfe.PlanTech.Application.UnitTests/Submissions/Commands/SubmissionCommandTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Submissions/Queries/GetLatestResponsesQueryTests.cs
tests/Dfe.PlanTech.Application.UnitTests/Submissions/Queries/SubmissionStatusProcessorTests.cs
tests/Dfe.PlanTech.Domain.UnitTests/Helpers/SubmissionStatusHelpersTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Controllers/CheckAnswersControllerTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Controllers/QuestionsControllerTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Controllers/RecommendationsControllerTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Routing/ChangeAnswersRouterTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Routing/CheckAnswersRouterTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Routing/GetQuestionBySlugRouterTests.cs
tests/Dfe.PlanTech.Web.UnitTests/Routing/GetRecommendationRouterTests.cs

Addresses ticket [#257799](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/257799)
Tile home page and onward journey v1
The design for the ticket is based on:
https://plantech.herokuapp.com/sprint14/homepage/homepage
- Updated home/topics page to use tiles
- Added YSA (your self-assessment) chunk on recommendations
- Added change your answers page
- Updated code logic to support the ability to submit and change completed submissions while retaining core functionality
- Removed/Added appropriate UI layout based on the prototype
- Added unit tests to support logic
run v1 feature branch locally, smoke test journey flows as expected. Submissions/changing answers works and allows you to keep submitting to update recommendations
Database update script to …

Merge Feat/257799/home page journey v1 into Development

---

src/Dfe.PlanTech.Web/Views/Recommendations/Content.cshtml
src/Dfe.PlanTech.Web/Views/Recommendations/YSA.cshtml

Addresses ticket [#265049](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/265049)
Removes bolding of date of last submission on the recommendation overview and your self assessment.

fix(265049): unbold submission date on recommendations

---

.github/workflows/infrastructure-deploy.yml
terraform/container-app/locals.tf
terraform/container-app/main-hosting.tf
terraform/container-app/variables.tf

Addresses ticket [253522](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/253522)
and
Addresses ticket [253518](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/253518)
Change the linked Entra ID to be that of a separate security group rather than the terraform service principal for security reasons. Also made a change to source the SQL Server firewall rules from the terraform variables key vault.
Have updated the key vault with the new security group Object ID and also added the firewall rules (as they were setup in the existing SQL Server resource).
- Changed SQL Admin linked Entra ID to be that of the separate security group (change in key vault secret value)
- Make use of the SQL Server firewall rules (also a value in …

Story(253522): SQL Admin change to Entra security group and add firewall rules

---

.github/pull_request_template.md

Currently the README links to `v1.0.0-beta.4` of the conventional commits spec.
This has been updated to `v1.0.0`
Additionally, I have switched the placeholder ticket link to `example.com` (to avoid accidental links to "real" placeholder domains).
Note the changes between the pre-release beta version 4 and the full release do not seem to be substantive / impactful - mostly relating to how breaking changes are defined/set.

docs: Update URLs in PR template

---

.github/workflows/e2e-tests.yml
.github/workflows/infrastructure-deploy.yml
.github/workflows/terraform-pr-check.yml
terraform/container-app/locals.tf
terraform/container-app/main-hosting.tf
terraform/container-app/providers.tf
terraform/container-app/redis.tf
terraform/container-app/variables.tf
terraform/container-app/versions.tf

Addresses ticket [253268](https://dfe-ssp.visualstudio.com/s190-schools-technology-services/_workitems/edit/253268)
Update version of [Shared Container app hosting module](https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting) in use in the container-app module.
In addition to the main change I have also made a change that allows for the defining of public access enabling for the Redis Cache per environment. This value will default to False but will be overridden if the terraform variables contains and appropriate variable set to true: redis_public_access_enabled = true
The reason for this is to allow the container app running as part of the E2E workflow (in the user agent) to be able to access the Redis cache from its external location. This workflow is only run …

Story(253268): Update main hosting module version used in container app terraform module

---

src/Dfe.PlanTech.Web/Views/Recommendations/SingleRecommendation.cshtml
src/Dfe.PlanTech.Web/Views/Shared/_SingleRecommendationLayout.cshtml

RecommendationsLayout has been split to SingleRecommendationsLayout. Fixes a bug where a duplicate beta header partial was being displayed at the bottom of the recommendations page on the MAT View.

Bug fix - duplicate beta header on MAT View

---

.github/workflows/code-pr-check.yml

Also, trigger the checks (incl. sonar) on more than just branches+PRs on main / development branches.
Note this is a copy of #1185 , but targeting the branch `development`.

Deal with the sonar warnings about deprecated config options, incorrect checkout depth, etc.
